#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : MuseScore
Version  : 3.4.2
Release  : 13
URL      : https://github.com/musescore/MuseScore/archive/v3.4.2/MuseScore-3.4.2.tar.gz
Source0  : https://github.com/musescore/MuseScore/archive/v3.4.2/MuseScore-3.4.2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause CC-BY-4.0 FTL GPL-2.0 GPL-3.0 LGPL-2.1 LGPL-3.0 MIT OFL-1.1 OpenSSL
Requires: MuseScore-bin = %{version}-%{release}
Requires: MuseScore-data = %{version}-%{release}
Requires: MuseScore-license = %{version}-%{release}
Requires: MuseScore-man = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-qmake
BuildRequires : freetype-dev
BuildRequires : libsndfile-dev
BuildRequires : libvorbis-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(Qt5QuickControls2)
BuildRequires : pkgconfig(Qt5QuickTemplates2)
BuildRequires : pkgconfig(alsa)
BuildRequires : pkgconfig(harfbuzz)
BuildRequires : pkgconfig(harfbuzz-icu)
BuildRequires : pkgconfig(libpulse)
BuildRequires : pkgconfig(portaudio-2.0)
BuildRequires : qtbase-dev mesa-dev
BuildRequires : qtsvg-dev
BuildRequires : qttools-dev
BuildRequires : qtwebengine-dev
BuildRequires : qtxmlpatterns-dev

%description
References
* Cakewalk® Synthesizers: From Presets to Power User, Second Edition
Simon Cann - Course Technology - 2009

%package bin
Summary: bin components for the MuseScore package.
Group: Binaries
Requires: MuseScore-data = %{version}-%{release}
Requires: MuseScore-license = %{version}-%{release}

%description bin
bin components for the MuseScore package.


%package data
Summary: data components for the MuseScore package.
Group: Data

%description data
data components for the MuseScore package.


%package license
Summary: license components for the MuseScore package.
Group: Default

%description license
license components for the MuseScore package.


%package man
Summary: man components for the MuseScore package.
Group: Default

%description man
man components for the MuseScore package.


%prep
%setup -q -n MuseScore-3.4.2
cd %{_builddir}/MuseScore-3.4.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1581108958
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake .. -DBUILD_WEBENGINE=OFF \
-DUSE_SYSTEM_FREETYPE=ON \
-DBUILD_LAME=OFF \
-DBUILD_JACK=OFF \
-DBUILD_PORTMIDI=OFF \
-DBUILD_PCH=OFF \
-DBUILD_AUTOUPDATE=OFF \
-DBUILD_CRASH_REPORTER=OFF
make  %{?_smp_mflags}  VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1581108958
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/MuseScore
cp %{_builddir}/MuseScore-3.4.2/LICENSE.GPL %{buildroot}/usr/share/package-licenses/MuseScore/c049b0fc74357466720414a795d9f65ce137c80c
cp %{_builddir}/MuseScore-3.4.2/LICENSE.rtf %{buildroot}/usr/share/package-licenses/MuseScore/71868dea6f409f4f93b882ec0af609c474486f1c
cp %{_builddir}/MuseScore-3.4.2/aeolus/COPYING %{buildroot}/usr/share/package-licenses/MuseScore/dfac199a7539a404407098a2541b9482279f690d
cp %{_builddir}/MuseScore-3.4.2/bww2mxml/COPYING %{buildroot}/usr/share/package-licenses/MuseScore/ae157c440dbbaa3bd959f20bbb07d37fe120ee23
cp %{_builddir}/MuseScore-3.4.2/effects/chorus/COPYING %{buildroot}/usr/share/package-licenses/MuseScore/dfac199a7539a404407098a2541b9482279f690d
cp %{_builddir}/MuseScore-3.4.2/fonts/campania/LICENSE %{buildroot}/usr/share/package-licenses/MuseScore/985b1df2e313174e602dc88a90e707eaf7255c84
cp %{_builddir}/MuseScore-3.4.2/mscore/data/icons/LICENSE.md %{buildroot}/usr/share/package-licenses/MuseScore/4f07b9483243913622f0a1737288d3c713fe4de1
cp %{_builddir}/MuseScore-3.4.2/mscore/licence.h %{buildroot}/usr/share/package-licenses/MuseScore/027b096c8b7204e698a28a370d49a8d4e8550ae2
cp %{_builddir}/MuseScore-3.4.2/share/wallpaper/COPYRIGHT %{buildroot}/usr/share/package-licenses/MuseScore/5a04ab8ef605c56d9f877ca3953c1b000293ea79
cp %{_builddir}/MuseScore-3.4.2/thirdparty/beatroot/COPYING %{buildroot}/usr/share/package-licenses/MuseScore/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
cp %{_builddir}/MuseScore-3.4.2/thirdparty/dtl/COPYING %{buildroot}/usr/share/package-licenses/MuseScore/f63d4e18fb18c853ad20439b07536d5447ff2864
cp %{_builddir}/MuseScore-3.4.2/thirdparty/freetype/docs/GPLv2.TXT %{buildroot}/usr/share/package-licenses/MuseScore/dac7127c82749e3107b53530289e1cd548860868
cp %{_builddir}/MuseScore-3.4.2/thirdparty/freetype/docs/LICENSE.TXT %{buildroot}/usr/share/package-licenses/MuseScore/265206b28e7c1b750b7e6ea27cc527a6cc6e7644
cp %{_builddir}/MuseScore-3.4.2/thirdparty/intervaltree/LICENSE %{buildroot}/usr/share/package-licenses/MuseScore/791271aeffb279bd99b7e13689494796cc18919a
cp %{_builddir}/MuseScore-3.4.2/thirdparty/openssl/LICENSE %{buildroot}/usr/share/package-licenses/MuseScore/719f3fb82a1b9d1ee828dbb43b2460c233320c72
cp %{_builddir}/MuseScore-3.4.2/thirdparty/portmidi/license.txt %{buildroot}/usr/share/package-licenses/MuseScore/50a53a89a8310af162c249cebfae96e4c42d5dcd
cp %{_builddir}/MuseScore-3.4.2/thirdparty/rtf2html/COPYING.LESSER %{buildroot}/usr/share/package-licenses/MuseScore/e60c2e780886f95df9c9ee36992b8edabec00bcc
cp %{_builddir}/MuseScore-3.4.2/thirdparty/singleapp/LICENSE.GPL3 %{buildroot}/usr/share/package-licenses/MuseScore/8624bcdae55baeef00cd11d5dfcfa60f68710a02
cp %{_builddir}/MuseScore-3.4.2/thirdparty/singleapp/LICENSE.LGPL %{buildroot}/usr/share/package-licenses/MuseScore/caeb68c46fa36651acf592771d09de7937926bb3
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/mscore
/usr/bin/musescore

%files data
%defattr(-,root,root,-)
/usr/share/applications/mscore.desktop
/usr/share/icons/hicolor/128x128/apps/mscore.png
/usr/share/icons/hicolor/16x16/apps/mscore.png
/usr/share/icons/hicolor/24x24/apps/mscore.png
/usr/share/icons/hicolor/32x32/apps/mscore.png
/usr/share/icons/hicolor/48x48/apps/mscore.png
/usr/share/icons/hicolor/48x48/mimetypes/application-vnd.recordare.musicxml+xml.png
/usr/share/icons/hicolor/48x48/mimetypes/application-vnd.recordare.musicxml.png
/usr/share/icons/hicolor/48x48/mimetypes/application-x-musescore+xml.png
/usr/share/icons/hicolor/48x48/mimetypes/application-x-musescore.png
/usr/share/icons/hicolor/512x512/apps/mscore.png
/usr/share/icons/hicolor/64x64/apps/mscore.png
/usr/share/icons/hicolor/96x96/apps/mscore.png
/usr/share/icons/hicolor/scalable/apps/mscore.svg
/usr/share/icons/hicolor/scalable/mimetypes/application-vnd.recordare.musicxml+xml.svg
/usr/share/icons/hicolor/scalable/mimetypes/application-vnd.recordare.musicxml.svg
/usr/share/icons/hicolor/scalable/mimetypes/application-x-musescore+xml.svg
/usr/share/icons/hicolor/scalable/mimetypes/application-x-musescore.svg
/usr/share/metainfo/org.musescore.MuseScore.appdata.xml
/usr/share/mime-packages/musescore.xml
/usr/share/mscore-3.4/demos/Brassed_Up.mscx
/usr/share/mscore-3.4/demos/Dynamic_Strings.mscx
/usr/share/mscore-3.4/demos/Fugue_1.mscx
/usr/share/mscore-3.4/demos/Reunion.mscz
/usr/share/mscore-3.4/demos/Unclaimed_Gift.mscx
/usr/share/mscore-3.4/instruments/instruments.xml
/usr/share/mscore-3.4/locale/languages.xml
/usr/share/mscore-3.4/manual/plugins/manual.css
/usr/share/mscore-3.4/manual/plugins/plugins3.html
/usr/share/mscore-3.4/plugins/abc_import.qml
/usr/share/mscore-3.4/plugins/colornotes.qml
/usr/share/mscore-3.4/plugins/createscore.qml
/usr/share/mscore-3.4/plugins/helloqml/helloqml.qml
/usr/share/mscore-3.4/plugins/helloqml/translations/locale_de.qm
/usr/share/mscore-3.4/plugins/helloqml/translations/locale_de.ts
/usr/share/mscore-3.4/plugins/notenames.qml
/usr/share/mscore-3.4/plugins/panel.qml
/usr/share/mscore-3.4/plugins/random.qml
/usr/share/mscore-3.4/plugins/random2.qml
/usr/share/mscore-3.4/plugins/run.qml
/usr/share/mscore-3.4/plugins/scorelist.qml
/usr/share/mscore-3.4/plugins/view.qml
/usr/share/mscore-3.4/plugins/walk.qml
/usr/share/mscore-3.4/sound/MuseScore_General.sf3
/usr/share/mscore-3.4/sound/MuseScore_General_License.md
/usr/share/mscore-3.4/styles/MuseJazz.mss
/usr/share/mscore-3.4/styles/cchords_muse.xml
/usr/share/mscore-3.4/styles/cchords_nrb.xml
/usr/share/mscore-3.4/styles/cchords_rb.xml
/usr/share/mscore-3.4/styles/cchords_sym.xml
/usr/share/mscore-3.4/styles/chords.xml
/usr/share/mscore-3.4/styles/chords_jazz.xml
/usr/share/mscore-3.4/styles/chords_std.xml
/usr/share/mscore-3.4/styles/jazzchords.xml
/usr/share/mscore-3.4/styles/stdchords.xml
/usr/share/mscore-3.4/templates/01-General/00-Blank.mscx
/usr/share/mscore-3.4/templates/01-General/01-Treble_Clef.mscx
/usr/share/mscore-3.4/templates/01-General/02-Bass_Clef.mscx
/usr/share/mscore-3.4/templates/01-General/03-Grand_Staff.mscx
/usr/share/mscore-3.4/templates/02-Choral/01-SATB.mscx
/usr/share/mscore-3.4/templates/02-Choral/02-SATB_+_Organ.mscx
/usr/share/mscore-3.4/templates/02-Choral/03-SATB_+_Piano.mscx
/usr/share/mscore-3.4/templates/02-Choral/04-SATB_Closed_Score.mscx
/usr/share/mscore-3.4/templates/02-Choral/05-SATB_Closed_Score_+_Organ.mscx
/usr/share/mscore-3.4/templates/02-Choral/06-SATB_Closed_Score_+_Piano.mscx
/usr/share/mscore-3.4/templates/02-Choral/07-Voice_+_Piano.mscx
/usr/share/mscore-3.4/templates/02-Choral/08-Barbershop_Quartet.mscx
/usr/share/mscore-3.4/templates/02-Choral/09-Liturgical_Unmetrical.mscx
/usr/share/mscore-3.4/templates/02-Choral/10-Liturgical_Unmetrical_+_Organ.mscx
/usr/share/mscore-3.4/templates/03-Chamber_Music/01-String_Quartet.mscx
/usr/share/mscore-3.4/templates/03-Chamber_Music/02-Wind_Quartet.mscx
/usr/share/mscore-3.4/templates/03-Chamber_Music/03-Wind_Quintet.mscx
/usr/share/mscore-3.4/templates/03-Chamber_Music/04-Saxophone_Quartet.mscx
/usr/share/mscore-3.4/templates/03-Chamber_Music/05-Brass_Quartet.mscx
/usr/share/mscore-3.4/templates/03-Chamber_Music/06-Brass_Quintet.mscx
/usr/share/mscore-3.4/templates/04-Solo/01-Guitar.mscx
/usr/share/mscore-3.4/templates/04-Solo/02-Guitar_+_Tablature.mscx
/usr/share/mscore-3.4/templates/04-Solo/03-Guitar_Tablature.mscx
/usr/share/mscore-3.4/templates/04-Solo/04-Piano.mscx
/usr/share/mscore-3.4/templates/05-Jazz/01-Jazz_Lead_Sheet.mscx
/usr/share/mscore-3.4/templates/05-Jazz/02-Big_Band.mscx
/usr/share/mscore-3.4/templates/05-Jazz/03-Jazz_Combo.mscx
/usr/share/mscore-3.4/templates/06-Popular/01-Rock_Band.mscx
/usr/share/mscore-3.4/templates/06-Popular/02-Bluegrass_Band.mscx
/usr/share/mscore-3.4/templates/07-Band_and_Percussion/01-Concert_Band.mscx
/usr/share/mscore-3.4/templates/07-Band_and_Percussion/02-Small_Concert_Band.mscx
/usr/share/mscore-3.4/templates/07-Band_and_Percussion/03-Brass_Band.mscx
/usr/share/mscore-3.4/templates/07-Band_and_Percussion/04-Marching_Band.mscx
/usr/share/mscore-3.4/templates/07-Band_and_Percussion/05-Small_Marching_Band.mscx
/usr/share/mscore-3.4/templates/07-Band_and_Percussion/06-Battery_Percussion.mscx
/usr/share/mscore-3.4/templates/07-Band_and_Percussion/07-Large_Pit_Percussion.mscx
/usr/share/mscore-3.4/templates/07-Band_and_Percussion/08-Small_Pit_Percussion.mscx
/usr/share/mscore-3.4/templates/07-Band_and_Percussion/09-European_Concert_Band.mscx
/usr/share/mscore-3.4/templates/08-Orchestral/01-Classical_Orchestra.mscx
/usr/share/mscore-3.4/templates/08-Orchestral/02-Symphony_Orchestra.mscx
/usr/share/mscore-3.4/templates/08-Orchestral/03-String_Orchestra.mscx
/usr/share/mscore-3.4/templates/drumset_fr.drm
/usr/share/mscore-3.4/templates/orchestral.drm
/usr/share/mscore-3.4/tours/autoplace.tour
/usr/share/mscore-3.4/tours/inspector.tour
/usr/share/mscore-3.4/tours/mmrest.tour
/usr/share/mscore-3.4/tours/navigate.tour
/usr/share/mscore-3.4/tours/noteinput.tour
/usr/share/mscore-3.4/tours/palette.tour
/usr/share/mscore-3.4/tours/select.tour
/usr/share/mscore-3.4/tours/spanner-drop-apply.tour
/usr/share/mscore-3.4/tours/timeline.tour
/usr/share/mscore-3.4/tours/welcome.tour
/usr/share/mscore-3.4/wallpaper/background1.png
/usr/share/mscore-3.4/wallpaper/paper1.png
/usr/share/mscore-3.4/wallpaper/paper2.png
/usr/share/mscore-3.4/wallpaper/paper3.png
/usr/share/mscore-3.4/wallpaper/paper4.png
/usr/share/mscore-3.4/wallpaper/paper5.png
/usr/share/mscore-3.4/wallpaper/paper6.png
/usr/share/mscore-3.4/wallpaper/paper7.png
/usr/share/mscore-3.4/workspaces/Advanced.workspace
/usr/share/mscore-3.4/workspaces/Basic.workspace

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/MuseScore/027b096c8b7204e698a28a370d49a8d4e8550ae2
/usr/share/package-licenses/MuseScore/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
/usr/share/package-licenses/MuseScore/265206b28e7c1b750b7e6ea27cc527a6cc6e7644
/usr/share/package-licenses/MuseScore/4f07b9483243913622f0a1737288d3c713fe4de1
/usr/share/package-licenses/MuseScore/50a53a89a8310af162c249cebfae96e4c42d5dcd
/usr/share/package-licenses/MuseScore/5a04ab8ef605c56d9f877ca3953c1b000293ea79
/usr/share/package-licenses/MuseScore/71868dea6f409f4f93b882ec0af609c474486f1c
/usr/share/package-licenses/MuseScore/719f3fb82a1b9d1ee828dbb43b2460c233320c72
/usr/share/package-licenses/MuseScore/791271aeffb279bd99b7e13689494796cc18919a
/usr/share/package-licenses/MuseScore/8624bcdae55baeef00cd11d5dfcfa60f68710a02
/usr/share/package-licenses/MuseScore/985b1df2e313174e602dc88a90e707eaf7255c84
/usr/share/package-licenses/MuseScore/ae157c440dbbaa3bd959f20bbb07d37fe120ee23
/usr/share/package-licenses/MuseScore/c049b0fc74357466720414a795d9f65ce137c80c
/usr/share/package-licenses/MuseScore/caeb68c46fa36651acf592771d09de7937926bb3
/usr/share/package-licenses/MuseScore/dac7127c82749e3107b53530289e1cd548860868
/usr/share/package-licenses/MuseScore/dfac199a7539a404407098a2541b9482279f690d
/usr/share/package-licenses/MuseScore/e60c2e780886f95df9c9ee36992b8edabec00bcc
/usr/share/package-licenses/MuseScore/f63d4e18fb18c853ad20439b07536d5447ff2864

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/mscore.1.gz
/usr/share/man/man1/musescore.1.gz
