#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v18
# autospec commit: 356da6275008
#
Name     : MuseScore
Version  : 4.3.2
Release  : 19
URL      : https://github.com/musescore/MuseScore/archive/v4.3.2/MuseScore-4.3.2.tar.gz
Source0  : https://github.com/musescore/MuseScore/archive/v4.3.2/MuseScore-4.3.2.tar.gz
Summary  : Shared and static libraries for LAME.
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause BSL-1.0 GFDL-1.2 GPL-2.0 GPL-3.0 ICU LGPL-2.0 LGPL-2.1 LGPL-3.0 MIT OFL-1.1
Requires: MuseScore-bin = %{version}-%{release}
Requires: MuseScore-data = %{version}-%{release}
Requires: MuseScore-license = %{version}-%{release}
Requires: MuseScore-man = %{version}-%{release}
BuildRequires : alsa-lib-dev
BuildRequires : buildreq-cmake
BuildRequires : bzip2-dev
BuildRequires : doxygen
BuildRequires : freetype-dev
BuildRequires : git
BuildRequires : glibc-dev
BuildRequires : googletest-dev
BuildRequires : libpng-dev
BuildRequires : libsndfile-dev
BuildRequires : libvorbis-dev
BuildRequires : pkg-config
BuildRequires : pkgconfig(Qt5NetworkAuth)
BuildRequires : pkgconfig(Qt5QuickControls2)
BuildRequires : pkgconfig(Qt5QuickTemplates2)
BuildRequires : pkgconfig(alsa)
BuildRequires : pkgconfig(bzip2)
BuildRequires : pkgconfig(flac)
BuildRequires : pkgconfig(flac++)
BuildRequires : pkgconfig(harfbuzz)
BuildRequires : pkgconfig(harfbuzz-icu)
BuildRequires : pkgconfig(jack)
BuildRequires : pkgconfig(libbrotlidec)
BuildRequires : pkgconfig(ogg)
BuildRequires : pkgconfig(opus)
BuildRequires : pkgconfig(portaudio-2.0)
BuildRequires : pkgconfig(sndfile)
BuildRequires : python3
BuildRequires : python3-dev
BuildRequires : qt6base-dev
BuildRequires : qtbase-dev
BuildRequires : qtbase-dev mesa-dev
BuildRequires : qtbase-lib
BuildRequires : qtdeclarative-dev
BuildRequires : qtsvg-dev
BuildRequires : qttools-dev
BuildRequires : qtwebengine-dev
BuildRequires : qtx11extras-dev
BuildRequires : qtxmlpatterns-dev
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Don-t-install-the-crashpad_handler.patch

%description
LAME is an educational tool to be used for learning about MP3 encoding.  The
goal of the LAME project is to use the open source model to improve the
psycho acoustics, noise shaping and speed of MP3.

%package bin
Summary: bin components for the MuseScore package.
Group: Binaries
Requires: MuseScore-data = %{version}-%{release}
Requires: MuseScore-license = %{version}-%{release}

%description bin
bin components for the MuseScore package.


%package data
Summary: data components for the MuseScore package.
Group: Data

%description data
data components for the MuseScore package.


%package license
Summary: license components for the MuseScore package.
Group: Default

%description license
license components for the MuseScore package.


%package man
Summary: man components for the MuseScore package.
Group: Default

%description man
man components for the MuseScore package.


%prep
%setup -q -n MuseScore-4.3.2
cd %{_builddir}/MuseScore-4.3.2
%patch -P 1 -p1

%build
## build_prepend content
# no prebuilt binaries
rm -f src/diagnostics/crashpad_handler/linux/x86-64/crashpad_handler
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1722277707
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake .. -DBUILD_AUTOUPDATE=OFF \
-DBUILD_CRASH_REPORTER=OFF \
-DBUILD_JACK=OFF \
-DBUILD_LAME=OFF \
-DBUILD_PCH=OFF \
-DBUILD_PORTMIDI=OFF \
-DBUILD_WEBENGINE=OFF \
-DINSTALL_GTEST=OFF \
-DMUE_COMPILE_USE_SYSTEM_FREETYPE=ON \
-DQMAKE:FILEPATH=/usr/lib64/qt5/bin/qmake  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1722277707
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/MuseScore
cp %{_builddir}/MuseScore-%{version}/LICENSE.txt %{buildroot}/usr/share/package-licenses/MuseScore/c6cdea5f044c95b68a1a36d69f81fff23474f9c1 || :
cp %{_builddir}/MuseScore-%{version}/build/PortableApps/Other/Source/LauncherLicense.txt %{buildroot}/usr/share/package-licenses/MuseScore/358f72786c97f5a0c5b1e591230c592c55b4ca13 || :
cp %{_builddir}/MuseScore-%{version}/build/packaging/LICENSE.rtf %{buildroot}/usr/share/package-licenses/MuseScore/d4e5c03abfb7553786ce54d884099069ba8f31d4 || :
cp %{_builddir}/MuseScore-%{version}/buildscripts/PortableApps/Other/Source/LauncherLicense.txt %{buildroot}/usr/share/package-licenses/MuseScore/358f72786c97f5a0c5b1e591230c592c55b4ca13 || :
cp %{_builddir}/MuseScore-%{version}/buildscripts/packaging/LICENSE.rtf %{buildroot}/usr/share/package-licenses/MuseScore/eca38fa1e18e17f07a86cca714336c565ecbfe70 || :
cp %{_builddir}/MuseScore-%{version}/fonts/bravura/LICENSE.txt %{buildroot}/usr/share/package-licenses/MuseScore/6b237c2d44e8956b794b2a9385d8667e8b9edd19 || :
cp %{_builddir}/MuseScore-%{version}/fonts/campania/LICENSE %{buildroot}/usr/share/package-licenses/MuseScore/985b1df2e313174e602dc88a90e707eaf7255c84 || :
cp %{_builddir}/MuseScore-%{version}/fonts/edwin/LICENSE.txt %{buildroot}/usr/share/package-licenses/MuseScore/828a74dd924a6c91227253e0579f7193cae14a2a || :
cp %{_builddir}/MuseScore-%{version}/fonts/leland/LICENSE.txt %{buildroot}/usr/share/package-licenses/MuseScore/f3e300332e94e8a9069525ab71eeebd02d2fc03c || :
cp %{_builddir}/MuseScore-%{version}/share/wallpapers/COPYRIGHT %{buildroot}/usr/share/package-licenses/MuseScore/5a04ab8ef605c56d9f877ca3953c1b000293ea79 || :
cp %{_builddir}/MuseScore-%{version}/src/braille/thirdparty/liblouis/COPYING %{buildroot}/usr/share/package-licenses/MuseScore/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
cp %{_builddir}/MuseScore-%{version}/src/braille/thirdparty/liblouis/COPYING.LESSER %{buildroot}/usr/share/package-licenses/MuseScore/01a6b4bf79aca9b556822601186afab86e8c4fbf || :
cp %{_builddir}/MuseScore-%{version}/src/braille/thirdparty/liblouis/License.md %{buildroot}/usr/share/package-licenses/MuseScore/731a8eff333b8f7053ab2220511b524c87a75923 || :
cp %{_builddir}/MuseScore-%{version}/src/framework/draw/thirdparty/freetype/freetype-2.13.1/docs/GPLv2.TXT %{buildroot}/usr/share/package-licenses/MuseScore/dac7127c82749e3107b53530289e1cd548860868 || :
cp %{_builddir}/MuseScore-%{version}/src/framework/global/thirdparty/deto_async/LICENSE %{buildroot}/usr/share/package-licenses/MuseScore/f13a717b2d147919f0849d6bb9671c1176e37a2e || :
cp %{_builddir}/MuseScore-%{version}/src/framework/global/thirdparty/kors_logger/LICENSE %{buildroot}/usr/share/package-licenses/MuseScore/f13a717b2d147919f0849d6bb9671c1176e37a2e || :
cp %{_builddir}/MuseScore-%{version}/src/framework/global/thirdparty/kors_profiler/LICENSE %{buildroot}/usr/share/package-licenses/MuseScore/f13a717b2d147919f0849d6bb9671c1176e37a2e || :
cp %{_builddir}/MuseScore-%{version}/src/framework/global/thirdparty/utfcpp-3.2.1/LICENSE %{buildroot}/usr/share/package-licenses/MuseScore/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90 || :
cp %{_builddir}/MuseScore-%{version}/thirdparty/KDDockWidgets/LICENSE.GPL.txt %{buildroot}/usr/share/package-licenses/MuseScore/59cc38bb6bd181744147688a463990a2b99b3ed9 || :
cp %{_builddir}/MuseScore-%{version}/thirdparty/KDDockWidgets/LICENSES/GPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/MuseScore/2a638514c87c4923c0570c55822620fad56f2a33 || :
cp %{_builddir}/MuseScore-%{version}/thirdparty/KDDockWidgets/LICENSES/GPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/MuseScore/6091db0aead0d90182b93d3c0d09ba93d188f907 || :
cp %{_builddir}/MuseScore-%{version}/thirdparty/beatroot/COPYING %{buildroot}/usr/share/package-licenses/MuseScore/06877624ea5c77efe3b7e39b0f909eda6e25a4ec || :
cp %{_builddir}/MuseScore-%{version}/thirdparty/dtl/COPYING %{buildroot}/usr/share/package-licenses/MuseScore/f63d4e18fb18c853ad20439b07536d5447ff2864 || :
cp %{_builddir}/MuseScore-%{version}/thirdparty/flac/flac-1.4.3/COPYING.FDL %{buildroot}/usr/share/package-licenses/MuseScore/bd75d59f9d7d9731bfabdc48ecd19e704d218e38 || :
cp %{_builddir}/MuseScore-%{version}/thirdparty/flac/flac-1.4.3/COPYING.GPL %{buildroot}/usr/share/package-licenses/MuseScore/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/MuseScore-%{version}/thirdparty/flac/flac-1.4.3/COPYING.LGPL %{buildroot}/usr/share/package-licenses/MuseScore/caeb68c46fa36651acf592771d09de7937926bb3 || :
cp %{_builddir}/MuseScore-%{version}/thirdparty/flac/flac-1.4.3/COPYING.Xiph %{buildroot}/usr/share/package-licenses/MuseScore/1359276e3578aaba3dce4310115e65ab54f6ba37 || :
cp %{_builddir}/MuseScore-%{version}/thirdparty/fluidsynth/fluidsynth-2.3.3/LICENSE %{buildroot}/usr/share/package-licenses/MuseScore/731a8eff333b8f7053ab2220511b524c87a75923 || :
cp %{_builddir}/MuseScore-%{version}/thirdparty/google_crashpad_client/LICENSE %{buildroot}/usr/share/package-licenses/MuseScore/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/MuseScore-%{version}/thirdparty/google_crashpad_client/third_party/mini_chromium/mini_chromium/base/third_party/icu/LICENSE %{buildroot}/usr/share/package-licenses/MuseScore/033ba4d37afbd624a0022253abf6241fd9f4d9f3 || :
cp %{_builddir}/MuseScore-%{version}/thirdparty/googletest/LICENSE %{buildroot}/usr/share/package-licenses/MuseScore/5a2314153eadadc69258a9429104cd11804ea304 || :
cp %{_builddir}/MuseScore-%{version}/thirdparty/intervaltree/LICENSE %{buildroot}/usr/share/package-licenses/MuseScore/791271aeffb279bd99b7e13689494796cc18919a || :
cp %{_builddir}/MuseScore-%{version}/thirdparty/lame/COPYING %{buildroot}/usr/share/package-licenses/MuseScore/1679b0cb5406c6e4624f779c02e32985497f7aa7 || :
cp %{_builddir}/MuseScore-%{version}/thirdparty/opus/COPYING %{buildroot}/usr/share/package-licenses/MuseScore/dfada97ba32cb44804736a7768104a06be91a4f7 || :
cp %{_builddir}/MuseScore-%{version}/thirdparty/opusenc/libopusenc-0.2.1/COPYING %{buildroot}/usr/share/package-licenses/MuseScore/76288bf672ef944e804a208117d80856f9a7d38d || :
cp %{_builddir}/MuseScore-%{version}/thirdparty/rtf2html/COPYING.LESSER %{buildroot}/usr/share/package-licenses/MuseScore/e60c2e780886f95df9c9ee36992b8edabec00bcc || :
cp %{_builddir}/MuseScore-%{version}/tools/bww2mxml/COPYING %{buildroot}/usr/share/package-licenses/MuseScore/ae157c440dbbaa3bd959f20bbb07d37fe120ee23 || :
export GOAMD64=v2
GOAMD64=v2
pushd clr-build
%make_install
popd
## install_append content
# Don't install extraneous stuff that belongs to other projects
rm -rf %{buildroot}/usr/include/gmock
rm -rf %{buildroot}/usr/include/gtest
rm -rf %{buildroot}/usr/include/kddockwidgets
rm -rf %{buildroot}/usr/include/opus
rm -rf %{buildroot}/usr/lib64/cmake/GTest
rm -rf %{buildroot}/usr/lib64/cmake/KDDockWidgets
rm -rf %{buildroot}/usr/lib64/pkgconfig/gmock*
rm -rf %{buildroot}/usr/lib64/pkgconfig/gtest*
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/mscore

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.musescore.MuseScore.desktop
/usr/share/icons/hicolor/128x128/apps/mscore.png
/usr/share/icons/hicolor/16x16/apps/mscore.png
/usr/share/icons/hicolor/24x24/apps/mscore.png
/usr/share/icons/hicolor/32x32/apps/mscore.png
/usr/share/icons/hicolor/48x48/apps/mscore.png
/usr/share/icons/hicolor/512x512/apps/mscore.png
/usr/share/icons/hicolor/512x512/mimetypes/application-x-musescore+xml.png
/usr/share/icons/hicolor/512x512/mimetypes/application-x-musescore.png
/usr/share/icons/hicolor/64x64/apps/mscore.png
/usr/share/icons/hicolor/96x96/apps/mscore.png
/usr/share/metainfo/org.musescore.MuseScore.appdata.xml
/usr/share/mime-packages/musescore.xml
/usr/share/mscore-4.3/autobotscripts/TC1.1_CreateSimpleScore.js
/usr/share/mscore-4.3/autobotscripts/TC1.2_CreateSimpleScoreWithRandomInstruments.js
/usr/share/mscore-4.3/autobotscripts/TC2_CreateSimpleScoreByTemplate.js
/usr/share/mscore-4.3/autobotscripts/TC3_UsingNoteInputToolbar.js
/usr/share/mscore-4.3/autobotscripts/TC4_UsingPalettes.js
/usr/share/mscore-4.3/autobotscripts/TC5_UsingInstruments.js
/usr/share/mscore-4.3/autobotscripts/TC6_UsingInspector_Note.js
/usr/share/mscore-4.3/autobotscripts/TC7_UsingExport.js
/usr/share/mscore-4.3/autobotscripts/TC8_EngravingText.js
/usr/share/mscore-4.3/autobotscripts/TC9_BigScore(perfomance).js
/usr/share/mscore-4.3/autobotscripts/data/Big_Score.mscz
/usr/share/mscore-4.3/autobotscripts/steps/Inspector.js
/usr/share/mscore-4.3/autobotscripts/steps/Instruments.js
/usr/share/mscore-4.3/autobotscripts/steps/Navigation.js
/usr/share/mscore-4.3/autobotscripts/steps/NewScore.js
/usr/share/mscore-4.3/autobotscripts/steps/NoteInput.js
/usr/share/mscore-4.3/autobotscripts/steps/Palette.js
/usr/share/mscore-4.3/autobotscripts/steps/Score.js
/usr/share/mscore-4.3/instruments/instruments.xml
/usr/share/mscore-4.3/instruments/orders.xml
/usr/share/mscore-4.3/instruments/string_tunings_presets.json
/usr/share/mscore-4.3/locale/instruments_af.qm
/usr/share/mscore-4.3/locale/instruments_ar.qm
/usr/share/mscore-4.3/locale/instruments_ar_DZ.qm
/usr/share/mscore-4.3/locale/instruments_ar_EG.qm
/usr/share/mscore-4.3/locale/instruments_ar_SD.qm
/usr/share/mscore-4.3/locale/instruments_ast.qm
/usr/share/mscore-4.3/locale/instruments_be.qm
/usr/share/mscore-4.3/locale/instruments_bg.qm
/usr/share/mscore-4.3/locale/instruments_br.qm
/usr/share/mscore-4.3/locale/instruments_ca.qm
/usr/share/mscore-4.3/locale/instruments_ca@valencia.qm
/usr/share/mscore-4.3/locale/instruments_cs.qm
/usr/share/mscore-4.3/locale/instruments_cy.qm
/usr/share/mscore-4.3/locale/instruments_da.qm
/usr/share/mscore-4.3/locale/instruments_de.qm
/usr/share/mscore-4.3/locale/instruments_el.qm
/usr/share/mscore-4.3/locale/instruments_en.qm
/usr/share/mscore-4.3/locale/instruments_en_GB.qm
/usr/share/mscore-4.3/locale/instruments_en_US.qm
/usr/share/mscore-4.3/locale/instruments_eo.qm
/usr/share/mscore-4.3/locale/instruments_es.qm
/usr/share/mscore-4.3/locale/instruments_et.qm
/usr/share/mscore-4.3/locale/instruments_eu.qm
/usr/share/mscore-4.3/locale/instruments_fa.qm
/usr/share/mscore-4.3/locale/instruments_fi.qm
/usr/share/mscore-4.3/locale/instruments_fil.qm
/usr/share/mscore-4.3/locale/instruments_fo.qm
/usr/share/mscore-4.3/locale/instruments_fr.qm
/usr/share/mscore-4.3/locale/instruments_ga.qm
/usr/share/mscore-4.3/locale/instruments_gd.qm
/usr/share/mscore-4.3/locale/instruments_gl.qm
/usr/share/mscore-4.3/locale/instruments_he.qm
/usr/share/mscore-4.3/locale/instruments_hi_IN.qm
/usr/share/mscore-4.3/locale/instruments_hr.qm
/usr/share/mscore-4.3/locale/instruments_hu.qm
/usr/share/mscore-4.3/locale/instruments_hy.qm
/usr/share/mscore-4.3/locale/instruments_id.qm
/usr/share/mscore-4.3/locale/instruments_ig.qm
/usr/share/mscore-4.3/locale/instruments_it.qm
/usr/share/mscore-4.3/locale/instruments_ja.qm
/usr/share/mscore-4.3/locale/instruments_ka.qm
/usr/share/mscore-4.3/locale/instruments_kab.qm
/usr/share/mscore-4.3/locale/instruments_ko.qm
/usr/share/mscore-4.3/locale/instruments_lt.qm
/usr/share/mscore-4.3/locale/instruments_lv.qm
/usr/share/mscore-4.3/locale/instruments_ml.qm
/usr/share/mscore-4.3/locale/instruments_mn_MN.qm
/usr/share/mscore-4.3/locale/instruments_mt.qm
/usr/share/mscore-4.3/locale/instruments_nb.qm
/usr/share/mscore-4.3/locale/instruments_nl.qm
/usr/share/mscore-4.3/locale/instruments_nn.qm
/usr/share/mscore-4.3/locale/instruments_pl.qm
/usr/share/mscore-4.3/locale/instruments_pt.qm
/usr/share/mscore-4.3/locale/instruments_pt_BR.qm
/usr/share/mscore-4.3/locale/instruments_ro.qm
/usr/share/mscore-4.3/locale/instruments_ru.qm
/usr/share/mscore-4.3/locale/instruments_scn.qm
/usr/share/mscore-4.3/locale/instruments_sk.qm
/usr/share/mscore-4.3/locale/instruments_sl.qm
/usr/share/mscore-4.3/locale/instruments_sr.qm
/usr/share/mscore-4.3/locale/instruments_sr_RS.qm
/usr/share/mscore-4.3/locale/instruments_sv.qm
/usr/share/mscore-4.3/locale/instruments_sv_SE.qm
/usr/share/mscore-4.3/locale/instruments_th.qm
/usr/share/mscore-4.3/locale/instruments_tr.qm
/usr/share/mscore-4.3/locale/instruments_uk.qm
/usr/share/mscore-4.3/locale/instruments_uz@Latn.qm
/usr/share/mscore-4.3/locale/instruments_vi.qm
/usr/share/mscore-4.3/locale/instruments_zh_CN.qm
/usr/share/mscore-4.3/locale/instruments_zh_HK.qm
/usr/share/mscore-4.3/locale/instruments_zh_TW.qm
/usr/share/mscore-4.3/locale/languages.json
/usr/share/mscore-4.3/locale/musescore_af.qm
/usr/share/mscore-4.3/locale/musescore_ar.qm
/usr/share/mscore-4.3/locale/musescore_ar_DZ.qm
/usr/share/mscore-4.3/locale/musescore_ar_EG.qm
/usr/share/mscore-4.3/locale/musescore_ar_SD.qm
/usr/share/mscore-4.3/locale/musescore_ast.qm
/usr/share/mscore-4.3/locale/musescore_be.qm
/usr/share/mscore-4.3/locale/musescore_bg.qm
/usr/share/mscore-4.3/locale/musescore_br.qm
/usr/share/mscore-4.3/locale/musescore_ca.qm
/usr/share/mscore-4.3/locale/musescore_ca@valencia.qm
/usr/share/mscore-4.3/locale/musescore_cs.qm
/usr/share/mscore-4.3/locale/musescore_cy.qm
/usr/share/mscore-4.3/locale/musescore_da.qm
/usr/share/mscore-4.3/locale/musescore_de.qm
/usr/share/mscore-4.3/locale/musescore_el.qm
/usr/share/mscore-4.3/locale/musescore_en.qm
/usr/share/mscore-4.3/locale/musescore_en_GB.qm
/usr/share/mscore-4.3/locale/musescore_en_US.qm
/usr/share/mscore-4.3/locale/musescore_eo.qm
/usr/share/mscore-4.3/locale/musescore_es.qm
/usr/share/mscore-4.3/locale/musescore_et.qm
/usr/share/mscore-4.3/locale/musescore_eu.qm
/usr/share/mscore-4.3/locale/musescore_fa.qm
/usr/share/mscore-4.3/locale/musescore_fi.qm
/usr/share/mscore-4.3/locale/musescore_fil.qm
/usr/share/mscore-4.3/locale/musescore_fo.qm
/usr/share/mscore-4.3/locale/musescore_fr.qm
/usr/share/mscore-4.3/locale/musescore_ga.qm
/usr/share/mscore-4.3/locale/musescore_gd.qm
/usr/share/mscore-4.3/locale/musescore_gl.qm
/usr/share/mscore-4.3/locale/musescore_he.qm
/usr/share/mscore-4.3/locale/musescore_hi_IN.qm
/usr/share/mscore-4.3/locale/musescore_hr.qm
/usr/share/mscore-4.3/locale/musescore_hu.qm
/usr/share/mscore-4.3/locale/musescore_hy.qm
/usr/share/mscore-4.3/locale/musescore_id.qm
/usr/share/mscore-4.3/locale/musescore_ig.qm
/usr/share/mscore-4.3/locale/musescore_it.qm
/usr/share/mscore-4.3/locale/musescore_ja.qm
/usr/share/mscore-4.3/locale/musescore_ka.qm
/usr/share/mscore-4.3/locale/musescore_kab.qm
/usr/share/mscore-4.3/locale/musescore_ko.qm
/usr/share/mscore-4.3/locale/musescore_lt.qm
/usr/share/mscore-4.3/locale/musescore_lv.qm
/usr/share/mscore-4.3/locale/musescore_ml.qm
/usr/share/mscore-4.3/locale/musescore_mn_MN.qm
/usr/share/mscore-4.3/locale/musescore_mt.qm
/usr/share/mscore-4.3/locale/musescore_nb.qm
/usr/share/mscore-4.3/locale/musescore_nl.qm
/usr/share/mscore-4.3/locale/musescore_nn.qm
/usr/share/mscore-4.3/locale/musescore_pl.qm
/usr/share/mscore-4.3/locale/musescore_pt.qm
/usr/share/mscore-4.3/locale/musescore_pt_BR.qm
/usr/share/mscore-4.3/locale/musescore_ro.qm
/usr/share/mscore-4.3/locale/musescore_ru.qm
/usr/share/mscore-4.3/locale/musescore_scn.qm
/usr/share/mscore-4.3/locale/musescore_sk.qm
/usr/share/mscore-4.3/locale/musescore_sl.qm
/usr/share/mscore-4.3/locale/musescore_sr.qm
/usr/share/mscore-4.3/locale/musescore_sr_RS.qm
/usr/share/mscore-4.3/locale/musescore_sv.qm
/usr/share/mscore-4.3/locale/musescore_sv_SE.qm
/usr/share/mscore-4.3/locale/musescore_th.qm
/usr/share/mscore-4.3/locale/musescore_tr.qm
/usr/share/mscore-4.3/locale/musescore_uk.qm
/usr/share/mscore-4.3/locale/musescore_uz@Latn.qm
/usr/share/mscore-4.3/locale/musescore_vi.qm
/usr/share/mscore-4.3/locale/musescore_zh_CN.qm
/usr/share/mscore-4.3/locale/musescore_zh_HK.qm
/usr/share/mscore-4.3/locale/musescore_zh_TW.qm
/usr/share/mscore-4.3/locale/qt_bg.qm
/usr/share/mscore-4.3/locale/qt_el.qm
/usr/share/mscore-4.3/locale/qt_eu.qm
/usr/share/mscore-4.3/locale/qt_gd.qm
/usr/share/mscore-4.3/locale/qt_id.qm
/usr/share/mscore-4.3/locale/qt_lv.qm
/usr/share/mscore-4.3/locale/qt_nb.qm
/usr/share/mscore-4.3/locale/qt_nl.qm
/usr/share/mscore-4.3/locale/qt_nl_BE.qm
/usr/share/mscore-4.3/locale/qt_pt_BR.qm
/usr/share/mscore-4.3/locale/qt_ro.qm
/usr/share/mscore-4.3/locale/qt_tr.qm
/usr/share/mscore-4.3/locale/qt_vi.qm
/usr/share/mscore-4.3/plugins/colornotes/color_notes.png
/usr/share/mscore-4.3/plugins/colornotes/colornotes.qml
/usr/share/mscore-4.3/plugins/courtesy_accidentals/accidentals.png
/usr/share/mscore-4.3/plugins/courtesy_accidentals/addCourtesyAccidentals.qml
/usr/share/mscore-4.3/plugins/courtesy_accidentals/configCourtesyAccidentals.qml
/usr/share/mscore-4.3/plugins/courtesy_accidentals/removeCourtesyAccidentals.qml
/usr/share/mscore-4.3/plugins/intervals/mirror-intervals-3.qml
/usr/share/mscore-4.3/plugins/intervals/mirror_intervals.png
/usr/share/mscore-4.3/plugins/lilyrics/lilyrics.png
/usr/share/mscore-4.3/plugins/lilyrics/lilyrics.qml
/usr/share/mscore-4.3/plugins/new_retrograde/NewRetrograde.qml
/usr/share/mscore-4.3/plugins/new_retrograde/retrograde.png
/usr/share/mscore-4.3/plugins/note_names/note_names.png
/usr/share/mscore-4.3/plugins/note_names/notenames.qml
/usr/share/mscore-4.3/plugins/tuning/modal_tuning.png
/usr/share/mscore-4.3/plugins/tuning/tuning.qml
/usr/share/mscore-4.3/plugins/tuning_modal/Modal_Tuning.qml
/usr/share/mscore-4.3/plugins/tuning_modal/Temperaments.qml
/usr/share/mscore-4.3/plugins/tuning_modal/modal_tuning.png
"/usr/share/mscore-4.3/sound/MS Basic.sf3"
"/usr/share/mscore-4.3/sound/MS Basic_License.md"
/usr/share/mscore-4.3/styles/MuseJazz.mss
/usr/share/mscore-4.3/styles/cchords_muse.xml
/usr/share/mscore-4.3/styles/cchords_nrb.xml
/usr/share/mscore-4.3/styles/cchords_rb.xml
/usr/share/mscore-4.3/styles/cchords_sym.xml
/usr/share/mscore-4.3/styles/chords.xml
/usr/share/mscore-4.3/styles/chords_jazz.xml
/usr/share/mscore-4.3/styles/chords_std.xml
/usr/share/mscore-4.3/styles/jazzchords.xml
/usr/share/mscore-4.3/styles/stdchords.xml
/usr/share/mscore-4.3/tables/Es-Es-G0.utb
/usr/share/mscore-4.3/tables/IPA-unicode-range.uti
/usr/share/mscore-4.3/tables/IPA.utb
/usr/share/mscore-4.3/tables/Lv-Lv-g1.utb
/usr/share/mscore-4.3/tables/Pl-Pl-g1.utb
/usr/share/mscore-4.3/tables/afr-za-g1.ctb
/usr/share/mscore-4.3/tables/afr-za-g2.ctb
/usr/share/mscore-4.3/tables/ar-ar-comp8.utb
/usr/share/mscore-4.3/tables/ar-ar-g1-core.uti
/usr/share/mscore-4.3/tables/ar-ar-g1.utb
/usr/share/mscore-4.3/tables/ar-ar-g2.ctb
/usr/share/mscore-4.3/tables/ar-ar-math.uti
/usr/share/mscore-4.3/tables/ar.tbl
/usr/share/mscore-4.3/tables/as-in-g1.utb
/usr/share/mscore-4.3/tables/as.tbl
/usr/share/mscore-4.3/tables/ascii-to-unicode.dis
/usr/share/mscore-4.3/tables/ascii-us-patterns.cti
/usr/share/mscore-4.3/tables/aw-in-g1.utb
/usr/share/mscore-4.3/tables/awa.tbl
/usr/share/mscore-4.3/tables/ba.utb
/usr/share/mscore-4.3/tables/be-in-g1.utb
/usr/share/mscore-4.3/tables/bel-comp.utb
/usr/share/mscore-4.3/tables/bel.utb
/usr/share/mscore-4.3/tables/bengali.cti
/usr/share/mscore-4.3/tables/bg.ctb
/usr/share/mscore-4.3/tables/bg.dis
/usr/share/mscore-4.3/tables/bg.tbl
/usr/share/mscore-4.3/tables/bg.utb
/usr/share/mscore-4.3/tables/bh.ctb
/usr/share/mscore-4.3/tables/bh.tbl
/usr/share/mscore-4.3/tables/bn.tbl
/usr/share/mscore-4.3/tables/bo.ctb
/usr/share/mscore-4.3/tables/bo.tbl
/usr/share/mscore-4.3/tables/boxes.ctb
/usr/share/mscore-4.3/tables/br-in-g1.utb
/usr/share/mscore-4.3/tables/bra.tbl
/usr/share/mscore-4.3/tables/braille-patterns.cti
/usr/share/mscore-4.3/tables/ca-chardefs.cti
/usr/share/mscore-4.3/tables/ca-g1.ctb
/usr/share/mscore-4.3/tables/ca.tbl
/usr/share/mscore-4.3/tables/chr-us-g1.ctb
/usr/share/mscore-4.3/tables/ckb-chardefs.cti
/usr/share/mscore-4.3/tables/ckb-g1.ctb
/usr/share/mscore-4.3/tables/ckb-translation.cti
/usr/share/mscore-4.3/tables/ckb.tbl
/usr/share/mscore-4.3/tables/compress.cti
/usr/share/mscore-4.3/tables/controlchars.cti
/usr/share/mscore-4.3/tables/cop-eg-comp8.utb
/usr/share/mscore-4.3/tables/corrections.cti
/usr/share/mscore-4.3/tables/countries.cti
/usr/share/mscore-4.3/tables/cs-chardefs.cti
/usr/share/mscore-4.3/tables/cs-comp8.utb
/usr/share/mscore-4.3/tables/cs-g1.ctb
/usr/share/mscore-4.3/tables/cs-translation.cti
/usr/share/mscore-4.3/tables/cs.tbl
/usr/share/mscore-4.3/tables/cy-cy-g1.utb
/usr/share/mscore-4.3/tables/cy-cy-g2.ctb
/usr/share/mscore-4.3/tables/cy.tbl
/usr/share/mscore-4.3/tables/da-dk-6miscChars.cti
/usr/share/mscore-4.3/tables/da-dk-6miscChars_1993.cti
/usr/share/mscore-4.3/tables/da-dk-8miscChars.cti
/usr/share/mscore-4.3/tables/da-dk-8miscChars_1993.cti
/usr/share/mscore-4.3/tables/da-dk-g08.ctb
/usr/share/mscore-4.3/tables/da-dk-g08_1993.ctb
/usr/share/mscore-4.3/tables/da-dk-g16-lit_1993.ctb
/usr/share/mscore-4.3/tables/da-dk-g16.ctb
/usr/share/mscore-4.3/tables/da-dk-g16_1993.ctb
/usr/share/mscore-4.3/tables/da-dk-g18.ctb
/usr/share/mscore-4.3/tables/da-dk-g18_1993.ctb
/usr/share/mscore-4.3/tables/da-dk-g2.dic
/usr/share/mscore-4.3/tables/da-dk-g26-lit_1993.ctb
/usr/share/mscore-4.3/tables/da-dk-g26.ctb
/usr/share/mscore-4.3/tables/da-dk-g26_1993.ctb
/usr/share/mscore-4.3/tables/da-dk-g26l-lit_1993.ctb
/usr/share/mscore-4.3/tables/da-dk-g26l_1993.ctb
/usr/share/mscore-4.3/tables/da-dk-g28.ctb
/usr/share/mscore-4.3/tables/da-dk-g28_1993.ctb
/usr/share/mscore-4.3/tables/da-dk-g28l_1993.ctb
/usr/share/mscore-4.3/tables/da-dk-g2_1993.dic
/usr/share/mscore-4.3/tables/da-dk-octobraille.dis
/usr/share/mscore-4.3/tables/da-dk-octobraille_1993.dis
/usr/share/mscore-4.3/tables/de-accents-detailed.cti
/usr/share/mscore-4.3/tables/de-accents.cti
/usr/share/mscore-4.3/tables/de-chardefs6.cti
/usr/share/mscore-4.3/tables/de-chardefs8.cti
/usr/share/mscore-4.3/tables/de-chess.ctb
/usr/share/mscore-4.3/tables/de-comp6.utb
/usr/share/mscore-4.3/tables/de-de-comp8.ctb
/usr/share/mscore-4.3/tables/de-de.dis
/usr/share/mscore-4.3/tables/de-eurobrl6.dis
/usr/share/mscore-4.3/tables/de-eurobrl6u.dis
/usr/share/mscore-4.3/tables/de-g0-core.uti
/usr/share/mscore-4.3/tables/de-g0-detailed.utb
/usr/share/mscore-4.3/tables/de-g0.utb
/usr/share/mscore-4.3/tables/de-g1-core-patterns.dic
/usr/share/mscore-4.3/tables/de-g1-core.cti
/usr/share/mscore-4.3/tables/de-g1-detailed.ctb
/usr/share/mscore-4.3/tables/de-g1.ctb
/usr/share/mscore-4.3/tables/de-g2-core-patterns.dic
/usr/share/mscore-4.3/tables/de-g2-core.cti
/usr/share/mscore-4.3/tables/de-g2-detailed.ctb
/usr/share/mscore-4.3/tables/de-g2.ctb
/usr/share/mscore-4.3/tables/devanagari.cti
/usr/share/mscore-4.3/tables/digits6Dots.uti
/usr/share/mscore-4.3/tables/digits6DotsPlusDot6.uti
/usr/share/mscore-4.3/tables/digits8Dots.uti
/usr/share/mscore-4.3/tables/dra.ctb
/usr/share/mscore-4.3/tables/dra.tbl
/usr/share/mscore-4.3/tables/el.ctb
/usr/share/mscore-4.3/tables/en-GB-g2.ctb
/usr/share/mscore-4.3/tables/en-chardefs.cti
/usr/share/mscore-4.3/tables/en-chess.ctb
/usr/share/mscore-4.3/tables/en-gb-comp8.ctb
/usr/share/mscore-4.3/tables/en-gb-g1.utb
/usr/share/mscore-4.3/tables/en-in-g1.ctb
/usr/share/mscore-4.3/tables/en-nabcc.utb
/usr/share/mscore-4.3/tables/en-ueb-chardefs.uti
/usr/share/mscore-4.3/tables/en-ueb-g1.ctb
/usr/share/mscore-4.3/tables/en-ueb-g2.ctb
/usr/share/mscore-4.3/tables/en-ueb-math.ctb
/usr/share/mscore-4.3/tables/en-us-brf.dis
/usr/share/mscore-4.3/tables/en-us-comp6.ctb
/usr/share/mscore-4.3/tables/en-us-comp8-ext.utb
/usr/share/mscore-4.3/tables/en-us-comp8.ctb
/usr/share/mscore-4.3/tables/en-us-compbrl.uti
/usr/share/mscore-4.3/tables/en-us-emphasis.uti
/usr/share/mscore-4.3/tables/en-us-g1.ctb
/usr/share/mscore-4.3/tables/en-us-g2.ctb
/usr/share/mscore-4.3/tables/en-us-interline.ctb
/usr/share/mscore-4.3/tables/en-us-mathtext.ctb
/usr/share/mscore-4.3/tables/en-us-symbols.mus
/usr/share/mscore-4.3/tables/en_CA.ctb
/usr/share/mscore-4.3/tables/en_CA.tbl
/usr/share/mscore-4.3/tables/en_GB.tbl
/usr/share/mscore-4.3/tables/en_US-comp8-ext.tbl
/usr/share/mscore-4.3/tables/en_US.tbl
/usr/share/mscore-4.3/tables/eo-g1-x-system.ctb
/usr/share/mscore-4.3/tables/eo-g1.ctb
/usr/share/mscore-4.3/tables/eo.tbl
/usr/share/mscore-4.3/tables/es-chardefs.cti
/usr/share/mscore-4.3/tables/es-g1.ctb
/usr/share/mscore-4.3/tables/es-g2.ctb
/usr/share/mscore-4.3/tables/es-new.dis
/usr/share/mscore-4.3/tables/es-old.dis
/usr/share/mscore-4.3/tables/es.tbl
/usr/share/mscore-4.3/tables/et-g0.utb
/usr/share/mscore-4.3/tables/et.ctb
/usr/share/mscore-4.3/tables/et.tbl
/usr/share/mscore-4.3/tables/ethio-g1.ctb
/usr/share/mscore-4.3/tables/eurodefs.cti
/usr/share/mscore-4.3/tables/fa-ir-comp8.ctb
/usr/share/mscore-4.3/tables/fa-ir-g1.utb
/usr/share/mscore-4.3/tables/fi-fi-8dot.ctb
/usr/share/mscore-4.3/tables/fi.utb
/usr/share/mscore-4.3/tables/fr-bfu-comp6.utb
/usr/share/mscore-4.3/tables/fr-bfu-comp68.cti
/usr/share/mscore-4.3/tables/fr-bfu-comp8.utb
/usr/share/mscore-4.3/tables/fr-bfu-g2.ctb
/usr/share/mscore-4.3/tables/fr.mus
/usr/share/mscore-4.3/tables/ga-g1.utb
/usr/share/mscore-4.3/tables/ga-g2.ctb
/usr/share/mscore-4.3/tables/gd.ctb
/usr/share/mscore-4.3/tables/gd.tbl
/usr/share/mscore-4.3/tables/gez.tbl
/usr/share/mscore-4.3/tables/gon.ctb
/usr/share/mscore-4.3/tables/gon.tbl
/usr/share/mscore-4.3/tables/gr-pl-comp8.uti
/usr/share/mscore-4.3/tables/grc-international-common.uti
/usr/share/mscore-4.3/tables/grc-international-composed.uti
/usr/share/mscore-4.3/tables/grc-international-decomposed.uti
/usr/share/mscore-4.3/tables/grc-international-en.utb
/usr/share/mscore-4.3/tables/gu-in-g1.utb
/usr/share/mscore-4.3/tables/gu.tbl
/usr/share/mscore-4.3/tables/gujarati.cti
/usr/share/mscore-4.3/tables/gurumuki.cti
/usr/share/mscore-4.3/tables/haw-us-g1.ctb
/usr/share/mscore-4.3/tables/he-IL-comp8.utb
/usr/share/mscore-4.3/tables/he-IL.utb
/usr/share/mscore-4.3/tables/hi-in-g1.utb
/usr/share/mscore-4.3/tables/hi.tbl
/usr/share/mscore-4.3/tables/hr-chardefs.cti
/usr/share/mscore-4.3/tables/hr-comp8.tbl
/usr/share/mscore-4.3/tables/hr-comp8.utb
/usr/share/mscore-4.3/tables/hr-digits.uti
/usr/share/mscore-4.3/tables/hr-g1.ctb
/usr/share/mscore-4.3/tables/hr-g1.tbl
/usr/share/mscore-4.3/tables/hr-translation.cti
/usr/share/mscore-4.3/tables/hu-backtranslate-correction.dis
/usr/share/mscore-4.3/tables/hu-backtranslate-word-corrections.cti
/usr/share/mscore-4.3/tables/hu-chardefs.cti
/usr/share/mscore-4.3/tables/hu-exceptionwords.cti
/usr/share/mscore-4.3/tables/hu-hu-comp8.ctb
/usr/share/mscore-4.3/tables/hu-hu-g1.ctb
/usr/share/mscore-4.3/tables/hu-hu-g1_braille_input.cti
/usr/share/mscore-4.3/tables/hu-hu-g2.ctb
/usr/share/mscore-4.3/tables/hu-hu-g2_exceptions.cti
/usr/share/mscore-4.3/tables/hu.tbl
/usr/share/mscore-4.3/tables/hy.ctb
/usr/share/mscore-4.3/tables/hy.tbl
/usr/share/mscore-4.3/tables/hyph_cs_CZ.dic
/usr/share/mscore-4.3/tables/hyph_da_DK.dic
/usr/share/mscore-4.3/tables/hyph_de_DE.dic
/usr/share/mscore-4.3/tables/hyph_en_US.dic
/usr/share/mscore-4.3/tables/hyph_eo.dic
/usr/share/mscore-4.3/tables/hyph_es_ES.dic
/usr/share/mscore-4.3/tables/hyph_fr_FR.dic
/usr/share/mscore-4.3/tables/hyph_hu_HU.dic
/usr/share/mscore-4.3/tables/hyph_it_IT.dic
/usr/share/mscore-4.3/tables/hyph_nb_NO.dic
/usr/share/mscore-4.3/tables/hyph_nl_NL.dic
/usr/share/mscore-4.3/tables/hyph_nn_NO.dic
/usr/share/mscore-4.3/tables/hyph_pl_PL.dic
/usr/share/mscore-4.3/tables/hyph_pt_PT.dic
/usr/share/mscore-4.3/tables/hyph_ru.dic
/usr/share/mscore-4.3/tables/hyph_sv_SE.dic
/usr/share/mscore-4.3/tables/is-chardefs6.cti
/usr/share/mscore-4.3/tables/is-chardefs8.cti
/usr/share/mscore-4.3/tables/is.ctb
/usr/share/mscore-4.3/tables/is.tbl
/usr/share/mscore-4.3/tables/it-it-comp6.utb
/usr/share/mscore-4.3/tables/it-it-comp8.utb
/usr/share/mscore-4.3/tables/it.mus
/usr/share/mscore-4.3/tables/it.tbl
/usr/share/mscore-4.3/tables/iu-ca-g1.ctb
/usr/share/mscore-4.3/tables/ja-kantenji.utb
/usr/share/mscore-4.3/tables/ka-in-g1.utb
/usr/share/mscore-4.3/tables/ka.utb
/usr/share/mscore-4.3/tables/kannada.cti
/usr/share/mscore-4.3/tables/kh-in-g1.utb
/usr/share/mscore-4.3/tables/kha.tbl
/usr/share/mscore-4.3/tables/kk.utb
/usr/share/mscore-4.3/tables/km-g1.utb
/usr/share/mscore-4.3/tables/kmr.tbl
/usr/share/mscore-4.3/tables/kn.tbl
/usr/share/mscore-4.3/tables/ko-2006-g1.ctb
/usr/share/mscore-4.3/tables/ko-2006-g2.ctb
/usr/share/mscore-4.3/tables/ko-2006.cti
/usr/share/mscore-4.3/tables/ko-chars.cti
/usr/share/mscore-4.3/tables/ko-g1-rules.cti
/usr/share/mscore-4.3/tables/ko-g1.ctb
/usr/share/mscore-4.3/tables/ko-g2-rules.cti
/usr/share/mscore-4.3/tables/ko-g2.ctb
/usr/share/mscore-4.3/tables/ko.cti
/usr/share/mscore-4.3/tables/kok.ctb
/usr/share/mscore-4.3/tables/kok.tbl
/usr/share/mscore-4.3/tables/kru.ctb
/usr/share/mscore-4.3/tables/kru.tbl
/usr/share/mscore-4.3/tables/ks-in-g1.utb
/usr/share/mscore-4.3/tables/latinLetterDef6Dots.uti
/usr/share/mscore-4.3/tables/latinLetterDef8Dots.uti
/usr/share/mscore-4.3/tables/latinLowercase.uti
/usr/share/mscore-4.3/tables/latinUppercaseComp6.uti
/usr/share/mscore-4.3/tables/lg-ug-g1.utb
/usr/share/mscore-4.3/tables/litdigits6Dots.uti
/usr/share/mscore-4.3/tables/litdigits6DotsPlusDot6.uti
/usr/share/mscore-4.3/tables/loweredDigits6Dots.uti
/usr/share/mscore-4.3/tables/loweredDigits8Dots.uti
/usr/share/mscore-4.3/tables/lt-6dot.tbl
/usr/share/mscore-4.3/tables/lt-6dot.utb
/usr/share/mscore-4.3/tables/lt.ctb
/usr/share/mscore-4.3/tables/lt.tbl
/usr/share/mscore-4.3/tables/lv.tbl
/usr/share/mscore-4.3/tables/malayalam.cti
/usr/share/mscore-4.3/tables/mao-nz-g1.ctb
/usr/share/mscore-4.3/tables/marburg_single_cell_defs.cti
/usr/share/mscore-4.3/tables/marburg_unicode_defs.cti
/usr/share/mscore-4.3/tables/ml-in-g1.utb
/usr/share/mscore-4.3/tables/ml.tbl
/usr/share/mscore-4.3/tables/mn-MN-common.cti
/usr/share/mscore-4.3/tables/mn-MN-g1.utb
/usr/share/mscore-4.3/tables/mn-MN-g2.ctb
/usr/share/mscore-4.3/tables/mn-in-g1.utb
/usr/share/mscore-4.3/tables/mni.tbl
/usr/share/mscore-4.3/tables/mr-in-g1.utb
/usr/share/mscore-4.3/tables/mr.tbl
/usr/share/mscore-4.3/tables/ms-my-g2.ctb
/usr/share/mscore-4.3/tables/mt.ctb
/usr/share/mscore-4.3/tables/mt.tbl
/usr/share/mscore-4.3/tables/mun.ctb
/usr/share/mscore-4.3/tables/mun.tbl
/usr/share/mscore-4.3/tables/mwr.ctb
/usr/share/mscore-4.3/tables/mwr.tbl
/usr/share/mscore-4.3/tables/my-g1.utb
/usr/share/mscore-4.3/tables/my-g2.ctb
/usr/share/mscore-4.3/tables/ne.ctb
/usr/share/mscore-4.3/tables/ne.tbl
/usr/share/mscore-4.3/tables/nemethdefs.cti
/usr/share/mscore-4.3/tables/nl-BE.dis
/usr/share/mscore-4.3/tables/nl-NL-g0.utb
/usr/share/mscore-4.3/tables/nl-chardefs.uti
/usr/share/mscore-4.3/tables/nl-comp8.utb
/usr/share/mscore-4.3/tables/nl.tbl
/usr/share/mscore-4.3/tables/no-no-8dot-fallback-6dot-g0.utb
/usr/share/mscore-4.3/tables/no-no-8dot.utb
/usr/share/mscore-4.3/tables/no-no-braillo-047-01.dis
/usr/share/mscore-4.3/tables/no-no-chardefs6.uti
/usr/share/mscore-4.3/tables/no-no-comp8.ctb
/usr/share/mscore-4.3/tables/no-no-g0.utb
/usr/share/mscore-4.3/tables/no-no-g1.ctb
/usr/share/mscore-4.3/tables/no-no-g2.ctb
/usr/share/mscore-4.3/tables/no-no-g3.ctb
/usr/share/mscore-4.3/tables/no-no-generic.ctb
/usr/share/mscore-4.3/tables/no-no-generic.dis
/usr/share/mscore-4.3/tables/no-no-latinLetterDef6Dots_diacritics.uti
/usr/share/mscore-4.3/tables/no-no.dis
/usr/share/mscore-4.3/tables/np-in-g1.utb
/usr/share/mscore-4.3/tables/nso-za-g1.utb
/usr/share/mscore-4.3/tables/nso-za-g2.ctb
/usr/share/mscore-4.3/tables/ny-mw.utb
/usr/share/mscore-4.3/tables/or-in-g1.utb
/usr/share/mscore-4.3/tables/or.tbl
/usr/share/mscore-4.3/tables/oriya.cti
/usr/share/mscore-4.3/tables/pa.tbl
/usr/share/mscore-4.3/tables/pi.ctb
/usr/share/mscore-4.3/tables/pi.tbl
/usr/share/mscore-4.3/tables/pl-pl-comp8.ctb
/usr/share/mscore-4.3/tables/pl.tbl
/usr/share/mscore-4.3/tables/printables.cti
/usr/share/mscore-4.3/tables/pt-pt-comp8.ctb
/usr/share/mscore-4.3/tables/pt-pt-g1.utb
/usr/share/mscore-4.3/tables/pt-pt-g2.ctb
/usr/share/mscore-4.3/tables/pt.tbl
/usr/share/mscore-4.3/tables/pu-in-g1.utb
/usr/share/mscore-4.3/tables/ro.ctb
/usr/share/mscore-4.3/tables/ro.tbl
/usr/share/mscore-4.3/tables/ru-brf.dis
/usr/share/mscore-4.3/tables/ru-compbrl.ctb
/usr/share/mscore-4.3/tables/ru-letters.dis
/usr/share/mscore-4.3/tables/ru-litbrl-detailed.utb
/usr/share/mscore-4.3/tables/ru-litbrl.ctb
/usr/share/mscore-4.3/tables/ru-ru-g1.ctb
/usr/share/mscore-4.3/tables/ru-unicode.dis
/usr/share/mscore-4.3/tables/ru.ctb
/usr/share/mscore-4.3/tables/rw-rw-g1.utb
/usr/share/mscore-4.3/tables/sa-in-g1.utb
/usr/share/mscore-4.3/tables/sa.tbl
/usr/share/mscore-4.3/tables/sah.utb
/usr/share/mscore-4.3/tables/sd.tbl
/usr/share/mscore-4.3/tables/se-se.ctb
/usr/share/mscore-4.3/tables/se-se.dis
/usr/share/mscore-4.3/tables/si-in-g1.utb
/usr/share/mscore-4.3/tables/sin.cti
/usr/share/mscore-4.3/tables/sin.utb
/usr/share/mscore-4.3/tables/sk-g1.ctb
/usr/share/mscore-4.3/tables/sk-sk-g1.utb
/usr/share/mscore-4.3/tables/sk-sk.utb
/usr/share/mscore-4.3/tables/sl-si-comp8.ctb
/usr/share/mscore-4.3/tables/sl-si-g1.utb
/usr/share/mscore-4.3/tables/sl.tbl
/usr/share/mscore-4.3/tables/smufl-symbols.mus
/usr/share/mscore-4.3/tables/sot-za-g1.ctb
/usr/share/mscore-4.3/tables/sot-za-g2.ctb
/usr/share/mscore-4.3/tables/spaces.uti
/usr/share/mscore-4.3/tables/sr-chardefs.cti
/usr/share/mscore-4.3/tables/sr-g1.ctb
/usr/share/mscore-4.3/tables/sr.tbl
/usr/share/mscore-4.3/tables/sv-1989.ctb
/usr/share/mscore-4.3/tables/sv-1996.ctb
/usr/share/mscore-4.3/tables/sv-g0.utb
/usr/share/mscore-4.3/tables/sv-g1.ctb
/usr/share/mscore-4.3/tables/sv-g2.ctb
/usr/share/mscore-4.3/tables/sw-ke-g1-2.ctb
/usr/share/mscore-4.3/tables/sw-ke-g1-3.ctb
/usr/share/mscore-4.3/tables/sw-ke-g1-4.ctb
/usr/share/mscore-4.3/tables/sw-ke-g1-5.ctb
/usr/share/mscore-4.3/tables/sw-ke-g1.utb
/usr/share/mscore-4.3/tables/sw-ke-g2.ctb
/usr/share/mscore-4.3/tables/ta-ta-g1.ctb
/usr/share/mscore-4.3/tables/ta.ctb
/usr/share/mscore-4.3/tables/ta.tbl
/usr/share/mscore-4.3/tables/tamil.cti
/usr/share/mscore-4.3/tables/te-in-g1.utb
/usr/share/mscore-4.3/tables/te.tbl
/usr/share/mscore-4.3/tables/telugu.cti
/usr/share/mscore-4.3/tables/text_nabcc.dis
/usr/share/mscore-4.3/tables/tr-g1.ctb
/usr/share/mscore-4.3/tables/tr-g2.ctb
/usr/share/mscore-4.3/tables/tr-g2.tbl
/usr/share/mscore-4.3/tables/tr.ctb
/usr/share/mscore-4.3/tables/tr.tbl
/usr/share/mscore-4.3/tables/tsn-za-g1.ctb
/usr/share/mscore-4.3/tables/tsn-za-g2.ctb
/usr/share/mscore-4.3/tables/tt.utb
/usr/share/mscore-4.3/tables/uk-comp.utb
/usr/share/mscore-4.3/tables/uk.utb
/usr/share/mscore-4.3/tables/ukchardefs.cti
/usr/share/mscore-4.3/tables/ukmaths_single_cell_defs.cti
/usr/share/mscore-4.3/tables/ukmaths_unicode_defs.cti
/usr/share/mscore-4.3/tables/uni-text.dis
/usr/share/mscore-4.3/tables/unicode-braille.utb
/usr/share/mscore-4.3/tables/unicode-to-ascii.dis
/usr/share/mscore-4.3/tables/unicode-without-blank.dis
/usr/share/mscore-4.3/tables/unicode.dis
/usr/share/mscore-4.3/tables/ur-pk-g1.utb
/usr/share/mscore-4.3/tables/ur-pk-g2.ctb
/usr/share/mscore-4.3/tables/us-table.dis
/usr/share/mscore-4.3/tables/uz-g1.utb
/usr/share/mscore-4.3/tables/ve-za-g1.utb
/usr/share/mscore-4.3/tables/ve-za-g2.ctb
/usr/share/mscore-4.3/tables/vi-charsdef.uti
/usr/share/mscore-4.3/tables/vi-lettersdef.uti
/usr/share/mscore-4.3/tables/vi-puncsdef.uti
/usr/share/mscore-4.3/tables/vi-saigon-g1.ctb
/usr/share/mscore-4.3/tables/vi-vn-g0.utb
/usr/share/mscore-4.3/tables/vi-vn-g1.ctb
/usr/share/mscore-4.3/tables/vi-vn-g2.ctb
/usr/share/mscore-4.3/tables/vi.ctb
/usr/share/mscore-4.3/tables/wiskunde-chardefs.cti
/usr/share/mscore-4.3/tables/wordcx.dis
/usr/share/mscore-4.3/tables/xh-za-g1.utb
/usr/share/mscore-4.3/tables/xh-za-g2.ctb
/usr/share/mscore-4.3/tables/zh-chn.ctb
/usr/share/mscore-4.3/tables/zh-hk.ctb
/usr/share/mscore-4.3/tables/zh-tw.ctb
/usr/share/mscore-4.3/tables/zh_CHN.tbl
/usr/share/mscore-4.3/tables/zh_HK.tbl
/usr/share/mscore-4.3/tables/zhcn-cbs.ctb
/usr/share/mscore-4.3/tables/zhcn-g1.ctb
/usr/share/mscore-4.3/tables/zhcn-g2.ctb
/usr/share/mscore-4.3/tables/zu-za-g1.utb
/usr/share/mscore-4.3/tables/zu-za-g2.ctb
/usr/share/mscore-4.3/templates/01-General/01-Treble_Clef/01-Treble_Clef.mscx
/usr/share/mscore-4.3/templates/01-General/01-Treble_Clef/META-INF/container.xml
/usr/share/mscore-4.3/templates/01-General/01-Treble_Clef/Thumbnails/thumbnail.png
/usr/share/mscore-4.3/templates/01-General/01-Treble_Clef/audiosettings.json
/usr/share/mscore-4.3/templates/01-General/01-Treble_Clef/score_style.mss
/usr/share/mscore-4.3/templates/01-General/01-Treble_Clef/viewsettings.json
/usr/share/mscore-4.3/templates/01-General/02-Bass_Clef/02-Bass_Clef.mscx
/usr/share/mscore-4.3/templates/01-General/02-Bass_Clef/META-INF/container.xml
/usr/share/mscore-4.3/templates/01-General/02-Bass_Clef/Thumbnails/thumbnail.png
/usr/share/mscore-4.3/templates/01-General/02-Bass_Clef/audiosettings.json
/usr/share/mscore-4.3/templates/01-General/02-Bass_Clef/score_style.mss
/usr/share/mscore-4.3/templates/01-General/02-Bass_Clef/viewsettings.json
/usr/share/mscore-4.3/templates/01-General/03-Grand_Staff/03-Grand_Staff.mscx
/usr/share/mscore-4.3/templates/01-General/03-Grand_Staff/META-INF/container.xml
/usr/share/mscore-4.3/templates/01-General/03-Grand_Staff/Thumbnails/thumbnail.png
/usr/share/mscore-4.3/templates/01-General/03-Grand_Staff/audiosettings.json
/usr/share/mscore-4.3/templates/01-General/03-Grand_Staff/score_style.mss
/usr/share/mscore-4.3/templates/01-General/03-Grand_Staff/viewsettings.json
/usr/share/mscore-4.3/templates/02-Choral/01-SATB/01-SATB.mscx
/usr/share/mscore-4.3/templates/02-Choral/01-SATB/META-INF/container.xml
/usr/share/mscore-4.3/templates/02-Choral/01-SATB/Thumbnails/thumbnail.png
/usr/share/mscore-4.3/templates/02-Choral/01-SATB/audiosettings.json
/usr/share/mscore-4.3/templates/02-Choral/01-SATB/score_style.mss
/usr/share/mscore-4.3/templates/02-Choral/01-SATB/viewsettings.json
/usr/share/mscore-4.3/templates/02-Choral/02-SATB_+_Organ/02-SATB_+_Organ.mscx
/usr/share/mscore-4.3/templates/02-Choral/02-SATB_+_Organ/META-INF/container.xml
/usr/share/mscore-4.3/templates/02-Choral/02-SATB_+_Organ/Thumbnails/thumbnail.png
/usr/share/mscore-4.3/templates/02-Choral/02-SATB_+_Organ/audiosettings.json
/usr/share/mscore-4.3/templates/02-Choral/02-SATB_+_Organ/score_style.mss
/usr/share/mscore-4.3/templates/02-Choral/02-SATB_+_Organ/viewsettings.json
/usr/share/mscore-4.3/templates/02-Choral/03-SATB_+_Piano/03-SATB_+_Piano.mscx
/usr/share/mscore-4.3/templates/02-Choral/03-SATB_+_Piano/META-INF/container.xml
/usr/share/mscore-4.3/templates/02-Choral/03-SATB_+_Piano/Thumbnails/thumbnail.png
/usr/share/mscore-4.3/templates/02-Choral/03-SATB_+_Piano/audiosettings.json
/usr/share/mscore-4.3/templates/02-Choral/03-SATB_+_Piano/score_style.mss
/usr/share/mscore-4.3/templates/02-Choral/03-SATB_+_Piano/viewsettings.json
/usr/share/mscore-4.3/templates/02-Choral/04-SATB_Closed_Score/04-SATB_Closed_Score.mscx
/usr/share/mscore-4.3/templates/02-Choral/04-SATB_Closed_Score/META-INF/container.xml
/usr/share/mscore-4.3/templates/02-Choral/04-SATB_Closed_Score/Thumbnails/thumbnail.png
/usr/share/mscore-4.3/templates/02-Choral/04-SATB_Closed_Score/audiosettings.json
/usr/share/mscore-4.3/templates/02-Choral/04-SATB_Closed_Score/score_style.mss
/usr/share/mscore-4.3/templates/02-Choral/04-SATB_Closed_Score/viewsettings.json
/usr/share/mscore-4.3/templates/02-Choral/05-SATB_Closed_Score_+_Organ/05-SATB_Closed_Score_+_Organ.mscx
/usr/share/mscore-4.3/templates/02-Choral/05-SATB_Closed_Score_+_Organ/META-INF/container.xml
/usr/share/mscore-4.3/templates/02-Choral/05-SATB_Closed_Score_+_Organ/Thumbnails/thumbnail.png
/usr/share/mscore-4.3/templates/02-Choral/05-SATB_Closed_Score_+_Organ/audiosettings.json
/usr/share/mscore-4.3/templates/02-Choral/05-SATB_Closed_Score_+_Organ/score_style.mss
/usr/share/mscore-4.3/templates/02-Choral/05-SATB_Closed_Score_+_Organ/viewsettings.json
/usr/share/mscore-4.3/templates/02-Choral/06-SATB_Closed_Score_+_Piano/06-SATB_Closed_Score_+_Piano.mscx
/usr/share/mscore-4.3/templates/02-Choral/06-SATB_Closed_Score_+_Piano/META-INF/container.xml
/usr/share/mscore-4.3/templates/02-Choral/06-SATB_Closed_Score_+_Piano/Thumbnails/thumbnail.png
/usr/share/mscore-4.3/templates/02-Choral/06-SATB_Closed_Score_+_Piano/audiosettings.json
/usr/share/mscore-4.3/templates/02-Choral/06-SATB_Closed_Score_+_Piano/score_style.mss
/usr/share/mscore-4.3/templates/02-Choral/06-SATB_Closed_Score_+_Piano/viewsettings.json
/usr/share/mscore-4.3/templates/02-Choral/07-Voice_+_Piano/07-Voice_+_Piano.mscx
/usr/share/mscore-4.3/templates/02-Choral/07-Voice_+_Piano/META-INF/container.xml
/usr/share/mscore-4.3/templates/02-Choral/07-Voice_+_Piano/Thumbnails/thumbnail.png
/usr/share/mscore-4.3/templates/02-Choral/07-Voice_+_Piano/audiosettings.json
/usr/share/mscore-4.3/templates/02-Choral/07-Voice_+_Piano/score_style.mss
/usr/share/mscore-4.3/templates/02-Choral/07-Voice_+_Piano/viewsettings.json
/usr/share/mscore-4.3/templates/02-Choral/08-Barbershop_Quartet_(Men)/08-Barbershop_Quartet_(Men).mscx
/usr/share/mscore-4.3/templates/02-Choral/08-Barbershop_Quartet_(Men)/META-INF/container.xml
/usr/share/mscore-4.3/templates/02-Choral/08-Barbershop_Quartet_(Men)/Thumbnails/thumbnail.png
/usr/share/mscore-4.3/templates/02-Choral/08-Barbershop_Quartet_(Men)/audiosettings.json
/usr/share/mscore-4.3/templates/02-Choral/08-Barbershop_Quartet_(Men)/score_style.mss
/usr/share/mscore-4.3/templates/02-Choral/08-Barbershop_Quartet_(Men)/viewsettings.json
/usr/share/mscore-4.3/templates/02-Choral/09-Barbershop_Quartet_(Women)/09-Barbershop_Quartet_(Women).mscx
/usr/share/mscore-4.3/templates/02-Choral/09-Barbershop_Quartet_(Women)/META-INF/container.xml
/usr/share/mscore-4.3/templates/02-Choral/09-Barbershop_Quartet_(Women)/Thumbnails/thumbnail.png
/usr/share/mscore-4.3/templates/02-Choral/09-Barbershop_Quartet_(Women)/audiosettings.json
/usr/share/mscore-4.3/templates/02-Choral/09-Barbershop_Quartet_(Women)/score_style.mss
/usr/share/mscore-4.3/templates/02-Choral/09-Barbershop_Quartet_(Women)/viewsettings.json
/usr/share/mscore-4.3/templates/02-Choral/10-Liturgical_Unmetrical/10-Liturgical_Unmetrical.mscx
/usr/share/mscore-4.3/templates/02-Choral/10-Liturgical_Unmetrical/META-INF/container.xml
/usr/share/mscore-4.3/templates/02-Choral/10-Liturgical_Unmetrical/Thumbnails/thumbnail.png
/usr/share/mscore-4.3/templates/02-Choral/10-Liturgical_Unmetrical/audiosettings.json
/usr/share/mscore-4.3/templates/02-Choral/10-Liturgical_Unmetrical/score_style.mss
/usr/share/mscore-4.3/templates/02-Choral/10-Liturgical_Unmetrical/viewsettings.json
/usr/share/mscore-4.3/templates/02-Choral/11-Liturgical_Unmetrical_+_Organ/11-Liturgical_Unmetrical_+_Organ.mscx
/usr/share/mscore-4.3/templates/02-Choral/11-Liturgical_Unmetrical_+_Organ/META-INF/container.xml
/usr/share/mscore-4.3/templates/02-Choral/11-Liturgical_Unmetrical_+_Organ/Thumbnails/thumbnail.png
/usr/share/mscore-4.3/templates/02-Choral/11-Liturgical_Unmetrical_+_Organ/audiosettings.json
/usr/share/mscore-4.3/templates/02-Choral/11-Liturgical_Unmetrical_+_Organ/score_style.mss
/usr/share/mscore-4.3/templates/02-Choral/11-Liturgical_Unmetrical_+_Organ/viewsettings.json
/usr/share/mscore-4.3/templates/03-Chamber_Music/01-String_Quartet/01-String_Quartet.mscx
/usr/share/mscore-4.3/templates/03-Chamber_Music/01-String_Quartet/META-INF/container.xml
/usr/share/mscore-4.3/templates/03-Chamber_Music/01-String_Quartet/Thumbnails/thumbnail.png
/usr/share/mscore-4.3/templates/03-Chamber_Music/01-String_Quartet/audiosettings.json
/usr/share/mscore-4.3/templates/03-Chamber_Music/01-String_Quartet/score_style.mss
/usr/share/mscore-4.3/templates/03-Chamber_Music/01-String_Quartet/viewsettings.json
/usr/share/mscore-4.3/templates/03-Chamber_Music/02-Wind_Quartet/02-Wind_Quartet.mscx
/usr/share/mscore-4.3/templates/03-Chamber_Music/02-Wind_Quartet/META-INF/container.xml
/usr/share/mscore-4.3/templates/03-Chamber_Music/02-Wind_Quartet/Thumbnails/thumbnail.png
/usr/share/mscore-4.3/templates/03-Chamber_Music/02-Wind_Quartet/audiosettings.json
/usr/share/mscore-4.3/templates/03-Chamber_Music/02-Wind_Quartet/score_style.mss
/usr/share/mscore-4.3/templates/03-Chamber_Music/02-Wind_Quartet/viewsettings.json
/usr/share/mscore-4.3/templates/03-Chamber_Music/03-Wind_Quintet/03-Wind_Quintet.mscx
/usr/share/mscore-4.3/templates/03-Chamber_Music/03-Wind_Quintet/META-INF/container.xml
/usr/share/mscore-4.3/templates/03-Chamber_Music/03-Wind_Quintet/Thumbnails/thumbnail.png
/usr/share/mscore-4.3/templates/03-Chamber_Music/03-Wind_Quintet/audiosettings.json
/usr/share/mscore-4.3/templates/03-Chamber_Music/03-Wind_Quintet/score_style.mss
/usr/share/mscore-4.3/templates/03-Chamber_Music/03-Wind_Quintet/viewsettings.json
/usr/share/mscore-4.3/templates/03-Chamber_Music/04-Saxophone_Quartet/04-Saxophone_Quartet.mscx
/usr/share/mscore-4.3/templates/03-Chamber_Music/04-Saxophone_Quartet/META-INF/container.xml
/usr/share/mscore-4.3/templates/03-Chamber_Music/04-Saxophone_Quartet/Thumbnails/thumbnail.png
/usr/share/mscore-4.3/templates/03-Chamber_Music/04-Saxophone_Quartet/audiosettings.json
/usr/share/mscore-4.3/templates/03-Chamber_Music/04-Saxophone_Quartet/score_style.mss
/usr/share/mscore-4.3/templates/03-Chamber_Music/04-Saxophone_Quartet/viewsettings.json
/usr/share/mscore-4.3/templates/03-Chamber_Music/05-Brass_Quartet/05-Brass_Quartet.mscx
/usr/share/mscore-4.3/templates/03-Chamber_Music/05-Brass_Quartet/META-INF/container.xml
/usr/share/mscore-4.3/templates/03-Chamber_Music/05-Brass_Quartet/Thumbnails/thumbnail.png
/usr/share/mscore-4.3/templates/03-Chamber_Music/05-Brass_Quartet/audiosettings.json
/usr/share/mscore-4.3/templates/03-Chamber_Music/05-Brass_Quartet/score_style.mss
/usr/share/mscore-4.3/templates/03-Chamber_Music/05-Brass_Quartet/viewsettings.json
/usr/share/mscore-4.3/templates/03-Chamber_Music/06-Brass_Quintet/06-Brass_Quintet.mscx
/usr/share/mscore-4.3/templates/03-Chamber_Music/06-Brass_Quintet/META-INF/container.xml
/usr/share/mscore-4.3/templates/03-Chamber_Music/06-Brass_Quintet/Thumbnails/thumbnail.png
/usr/share/mscore-4.3/templates/03-Chamber_Music/06-Brass_Quintet/audiosettings.json
/usr/share/mscore-4.3/templates/03-Chamber_Music/06-Brass_Quintet/score_style.mss
/usr/share/mscore-4.3/templates/03-Chamber_Music/06-Brass_Quintet/viewsettings.json
/usr/share/mscore-4.3/templates/04-Solo/01-Guitar/01-Guitar.mscx
/usr/share/mscore-4.3/templates/04-Solo/01-Guitar/META-INF/container.xml
/usr/share/mscore-4.3/templates/04-Solo/01-Guitar/Thumbnails/thumbnail.png
/usr/share/mscore-4.3/templates/04-Solo/01-Guitar/audiosettings.json
/usr/share/mscore-4.3/templates/04-Solo/01-Guitar/score_style.mss
/usr/share/mscore-4.3/templates/04-Solo/01-Guitar/viewsettings.json
/usr/share/mscore-4.3/templates/04-Solo/02-Guitar_+_Tablature/02-Guitar_+_Tablature.mscx
/usr/share/mscore-4.3/templates/04-Solo/02-Guitar_+_Tablature/META-INF/container.xml
/usr/share/mscore-4.3/templates/04-Solo/02-Guitar_+_Tablature/Thumbnails/thumbnail.png
/usr/share/mscore-4.3/templates/04-Solo/02-Guitar_+_Tablature/audiosettings.json
/usr/share/mscore-4.3/templates/04-Solo/02-Guitar_+_Tablature/score_style.mss
/usr/share/mscore-4.3/templates/04-Solo/02-Guitar_+_Tablature/viewsettings.json
/usr/share/mscore-4.3/templates/04-Solo/03-Guitar_Tablature/03-Guitar_Tablature.mscx
/usr/share/mscore-4.3/templates/04-Solo/03-Guitar_Tablature/META-INF/container.xml
/usr/share/mscore-4.3/templates/04-Solo/03-Guitar_Tablature/Thumbnails/thumbnail.png
/usr/share/mscore-4.3/templates/04-Solo/03-Guitar_Tablature/audiosettings.json
/usr/share/mscore-4.3/templates/04-Solo/03-Guitar_Tablature/score_style.mss
/usr/share/mscore-4.3/templates/04-Solo/03-Guitar_Tablature/viewsettings.json
/usr/share/mscore-4.3/templates/04-Solo/04-Piano/04-Piano.mscx
/usr/share/mscore-4.3/templates/04-Solo/04-Piano/META-INF/container.xml
/usr/share/mscore-4.3/templates/04-Solo/04-Piano/Thumbnails/thumbnail.png
/usr/share/mscore-4.3/templates/04-Solo/04-Piano/audiosettings.json
/usr/share/mscore-4.3/templates/04-Solo/04-Piano/score_style.mss
/usr/share/mscore-4.3/templates/04-Solo/04-Piano/viewsettings.json
/usr/share/mscore-4.3/templates/05-Jazz/01-Jazz_Lead_Sheet/01-Jazz_Lead_Sheet.mscx
/usr/share/mscore-4.3/templates/05-Jazz/01-Jazz_Lead_Sheet/META-INF/container.xml
/usr/share/mscore-4.3/templates/05-Jazz/01-Jazz_Lead_Sheet/Thumbnails/thumbnail.png
/usr/share/mscore-4.3/templates/05-Jazz/01-Jazz_Lead_Sheet/audiosettings.json
/usr/share/mscore-4.3/templates/05-Jazz/01-Jazz_Lead_Sheet/score_style.mss
/usr/share/mscore-4.3/templates/05-Jazz/01-Jazz_Lead_Sheet/viewsettings.json
/usr/share/mscore-4.3/templates/05-Jazz/02-Big_Band/02-Big_Band.mscx
/usr/share/mscore-4.3/templates/05-Jazz/02-Big_Band/META-INF/container.xml
/usr/share/mscore-4.3/templates/05-Jazz/02-Big_Band/Thumbnails/thumbnail.png
/usr/share/mscore-4.3/templates/05-Jazz/02-Big_Band/audiosettings.json
/usr/share/mscore-4.3/templates/05-Jazz/02-Big_Band/score_style.mss
/usr/share/mscore-4.3/templates/05-Jazz/02-Big_Band/viewsettings.json
/usr/share/mscore-4.3/templates/05-Jazz/03-Jazz_Combo/03-Jazz_Combo.mscx
/usr/share/mscore-4.3/templates/05-Jazz/03-Jazz_Combo/META-INF/container.xml
/usr/share/mscore-4.3/templates/05-Jazz/03-Jazz_Combo/Thumbnails/thumbnail.png
/usr/share/mscore-4.3/templates/05-Jazz/03-Jazz_Combo/audiosettings.json
/usr/share/mscore-4.3/templates/05-Jazz/03-Jazz_Combo/score_style.mss
/usr/share/mscore-4.3/templates/05-Jazz/03-Jazz_Combo/viewsettings.json
/usr/share/mscore-4.3/templates/06-Popular/01-Rock_Band/01-Rock_Band.mscx
/usr/share/mscore-4.3/templates/06-Popular/01-Rock_Band/META-INF/container.xml
/usr/share/mscore-4.3/templates/06-Popular/01-Rock_Band/Thumbnails/thumbnail.png
/usr/share/mscore-4.3/templates/06-Popular/01-Rock_Band/audiosettings.json
/usr/share/mscore-4.3/templates/06-Popular/01-Rock_Band/score_style.mss
/usr/share/mscore-4.3/templates/06-Popular/01-Rock_Band/viewsettings.json
/usr/share/mscore-4.3/templates/06-Popular/02-Bluegrass_Band/02-Bluegrass_Band.mscx
/usr/share/mscore-4.3/templates/06-Popular/02-Bluegrass_Band/META-INF/container.xml
/usr/share/mscore-4.3/templates/06-Popular/02-Bluegrass_Band/Thumbnails/thumbnail.png
/usr/share/mscore-4.3/templates/06-Popular/02-Bluegrass_Band/audiosettings.json
/usr/share/mscore-4.3/templates/06-Popular/02-Bluegrass_Band/score_style.mss
/usr/share/mscore-4.3/templates/06-Popular/02-Bluegrass_Band/viewsettings.json
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/01-Concert_Band/01-Concert_Band.mscx
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/01-Concert_Band/META-INF/container.xml
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/01-Concert_Band/Thumbnails/thumbnail.png
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/01-Concert_Band/audiosettings.json
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/01-Concert_Band/score_style.mss
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/01-Concert_Band/viewsettings.json
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/02-Small_Concert_Band/02-Small_Concert_Band.mscx
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/02-Small_Concert_Band/META-INF/container.xml
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/02-Small_Concert_Band/Thumbnails/thumbnail.png
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/02-Small_Concert_Band/audiosettings.json
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/02-Small_Concert_Band/score_style.mss
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/02-Small_Concert_Band/viewsettings.json
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/03-Brass_Band/03-Brass_Band.mscx
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/03-Brass_Band/META-INF/container.xml
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/03-Brass_Band/Thumbnails/thumbnail.png
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/03-Brass_Band/audiosettings.json
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/03-Brass_Band/score_style.mss
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/03-Brass_Band/viewsettings.json
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/04-Marching_Band/04-Marching_Band.mscx
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/04-Marching_Band/META-INF/container.xml
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/04-Marching_Band/Thumbnails/thumbnail.png
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/04-Marching_Band/audiosettings.json
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/04-Marching_Band/score_style.mss
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/04-Marching_Band/viewsettings.json
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/05-Small_Marching_Band/05-Small_Marching_Band.mscx
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/05-Small_Marching_Band/META-INF/container.xml
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/05-Small_Marching_Band/Thumbnails/thumbnail.png
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/05-Small_Marching_Band/audiosettings.json
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/05-Small_Marching_Band/score_style.mss
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/05-Small_Marching_Band/viewsettings.json
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/06-Battery_Percussion/06-Battery_Percussion.mscx
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/06-Battery_Percussion/META-INF/container.xml
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/06-Battery_Percussion/Thumbnails/thumbnail.png
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/06-Battery_Percussion/audiosettings.json
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/06-Battery_Percussion/score_style.mss
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/06-Battery_Percussion/viewsettings.json
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/07-Large_Pit_Percussion/07-Large_Pit_Percussion.mscx
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/07-Large_Pit_Percussion/META-INF/container.xml
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/07-Large_Pit_Percussion/Thumbnails/thumbnail.png
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/07-Large_Pit_Percussion/audiosettings.json
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/07-Large_Pit_Percussion/score_style.mss
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/07-Large_Pit_Percussion/viewsettings.json
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/08-Small_Pit_Percussion/08-Small_Pit_Percussion.mscx
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/08-Small_Pit_Percussion/META-INF/container.xml
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/08-Small_Pit_Percussion/Thumbnails/thumbnail.png
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/08-Small_Pit_Percussion/audiosettings.json
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/08-Small_Pit_Percussion/score_style.mss
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/08-Small_Pit_Percussion/viewsettings.json
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/09-European_Concert_Band/09-European_Concert_Band.mscx
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/09-European_Concert_Band/META-INF/container.xml
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/09-European_Concert_Band/Thumbnails/thumbnail.png
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/09-European_Concert_Band/audiosettings.json
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/09-European_Concert_Band/score_style.mss
/usr/share/mscore-4.3/templates/07-Band_and_Percussion/09-European_Concert_Band/viewsettings.json
/usr/share/mscore-4.3/templates/08-Orchestral/01-Classical_Orchestra/01-Classical_Orchestra.mscx
/usr/share/mscore-4.3/templates/08-Orchestral/01-Classical_Orchestra/META-INF/container.xml
/usr/share/mscore-4.3/templates/08-Orchestral/01-Classical_Orchestra/Thumbnails/thumbnail.png
/usr/share/mscore-4.3/templates/08-Orchestral/01-Classical_Orchestra/audiosettings.json
/usr/share/mscore-4.3/templates/08-Orchestral/01-Classical_Orchestra/score_style.mss
/usr/share/mscore-4.3/templates/08-Orchestral/01-Classical_Orchestra/viewsettings.json
/usr/share/mscore-4.3/templates/08-Orchestral/02-Symphony_Orchestra/02-Symphony_Orchestra.mscx
/usr/share/mscore-4.3/templates/08-Orchestral/02-Symphony_Orchestra/META-INF/container.xml
/usr/share/mscore-4.3/templates/08-Orchestral/02-Symphony_Orchestra/Thumbnails/thumbnail.png
/usr/share/mscore-4.3/templates/08-Orchestral/02-Symphony_Orchestra/audiosettings.json
/usr/share/mscore-4.3/templates/08-Orchestral/02-Symphony_Orchestra/score_style.mss
/usr/share/mscore-4.3/templates/08-Orchestral/02-Symphony_Orchestra/viewsettings.json
/usr/share/mscore-4.3/templates/08-Orchestral/03-String_Orchestra/03-String_Orchestra.mscx
/usr/share/mscore-4.3/templates/08-Orchestral/03-String_Orchestra/META-INF/container.xml
/usr/share/mscore-4.3/templates/08-Orchestral/03-String_Orchestra/Thumbnails/thumbnail.png
/usr/share/mscore-4.3/templates/08-Orchestral/03-String_Orchestra/audiosettings.json
/usr/share/mscore-4.3/templates/08-Orchestral/03-String_Orchestra/score_style.mss
/usr/share/mscore-4.3/templates/08-Orchestral/03-String_Orchestra/viewsettings.json
/usr/share/mscore-4.3/templates/My_First_Score.mscx
/usr/share/mscore-4.3/templates/categories.json
/usr/share/mscore-4.3/templates/drumset_fr.drm
/usr/share/mscore-4.3/templates/orchestral.drm
/usr/share/mscore-4.3/wallpapers/background1.png
/usr/share/mscore-4.3/wallpapers/paper1.png
/usr/share/mscore-4.3/wallpapers/paper2.png
/usr/share/mscore-4.3/wallpapers/paper3.png
/usr/share/mscore-4.3/wallpapers/paper4.png
/usr/share/mscore-4.3/wallpapers/paper5.png
/usr/share/mscore-4.3/wallpapers/paper6.png
/usr/share/mscore-4.3/wallpapers/paper7.png

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/MuseScore/01a6b4bf79aca9b556822601186afab86e8c4fbf
/usr/share/package-licenses/MuseScore/033ba4d37afbd624a0022253abf6241fd9f4d9f3
/usr/share/package-licenses/MuseScore/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
/usr/share/package-licenses/MuseScore/1359276e3578aaba3dce4310115e65ab54f6ba37
/usr/share/package-licenses/MuseScore/1679b0cb5406c6e4624f779c02e32985497f7aa7
/usr/share/package-licenses/MuseScore/2a638514c87c4923c0570c55822620fad56f2a33
/usr/share/package-licenses/MuseScore/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/MuseScore/358f72786c97f5a0c5b1e591230c592c55b4ca13
/usr/share/package-licenses/MuseScore/3cba29011be2b9d59f6204d6fa0a386b1b2dbd90
/usr/share/package-licenses/MuseScore/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/MuseScore/59cc38bb6bd181744147688a463990a2b99b3ed9
/usr/share/package-licenses/MuseScore/5a04ab8ef605c56d9f877ca3953c1b000293ea79
/usr/share/package-licenses/MuseScore/5a2314153eadadc69258a9429104cd11804ea304
/usr/share/package-licenses/MuseScore/6091db0aead0d90182b93d3c0d09ba93d188f907
/usr/share/package-licenses/MuseScore/6b237c2d44e8956b794b2a9385d8667e8b9edd19
/usr/share/package-licenses/MuseScore/731a8eff333b8f7053ab2220511b524c87a75923
/usr/share/package-licenses/MuseScore/76288bf672ef944e804a208117d80856f9a7d38d
/usr/share/package-licenses/MuseScore/791271aeffb279bd99b7e13689494796cc18919a
/usr/share/package-licenses/MuseScore/828a74dd924a6c91227253e0579f7193cae14a2a
/usr/share/package-licenses/MuseScore/8624bcdae55baeef00cd11d5dfcfa60f68710a02
/usr/share/package-licenses/MuseScore/985b1df2e313174e602dc88a90e707eaf7255c84
/usr/share/package-licenses/MuseScore/ae157c440dbbaa3bd959f20bbb07d37fe120ee23
/usr/share/package-licenses/MuseScore/bd75d59f9d7d9731bfabdc48ecd19e704d218e38
/usr/share/package-licenses/MuseScore/c6cdea5f044c95b68a1a36d69f81fff23474f9c1
/usr/share/package-licenses/MuseScore/caeb68c46fa36651acf592771d09de7937926bb3
/usr/share/package-licenses/MuseScore/d4e5c03abfb7553786ce54d884099069ba8f31d4
/usr/share/package-licenses/MuseScore/dac7127c82749e3107b53530289e1cd548860868
/usr/share/package-licenses/MuseScore/dfada97ba32cb44804736a7768104a06be91a4f7
/usr/share/package-licenses/MuseScore/e60c2e780886f95df9c9ee36992b8edabec00bcc
/usr/share/package-licenses/MuseScore/eca38fa1e18e17f07a86cca714336c565ecbfe70
/usr/share/package-licenses/MuseScore/f13a717b2d147919f0849d6bb9671c1176e37a2e
/usr/share/package-licenses/MuseScore/f3e300332e94e8a9069525ab71eeebd02d2fc03c
/usr/share/package-licenses/MuseScore/f63d4e18fb18c853ad20439b07536d5447ff2864

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/mscore.1.gz
/usr/share/man/man1/musescore.1.gz
